"""
ORCA QM/MM Input File Writer

Generates ORCA .inp files and prepares PDB coordinate files with
occupancy/B-factor columns set for QM atom and active atom marking.
"""

import os
from datetime import datetime
from pathlib import Path
from typing import Optional

import parmed

from proprep.orca_prep.orca_data_structures import ORCAQMMMSetup, compress_indices


class ORCAWriter:
    """
    Writes ORCA QM/MM input files (.inp) and coordinate files (PDB).

    The writer generates:
    1. An ORCA .inp file with the simple input line, %pal, %maxcore, %qmmm blocks
    2. A PDB file with occupancy = 1.0 for QM atoms, B-factor = 1.0 for active atoms
    3. An optional convenience shell script for running the calculation
    """

    def __init__(self, setup: ORCAQMMMSetup):
        """
        Initialize the writer with a complete ORCA QM/MM setup.

        Args:
            setup: ORCAQMMMSetup with all configuration populated
        """
        self.setup = setup

    def build_simple_input_line(self) -> str:
        """
        Build the ORCA '!' simple input line.

        Returns:
            The simple input line string (without the leading '!')
        """
        parts = ["QMMM"]

        if self.setup.qmmm_setup_only:
            parts.append("QMMMSetup")

        parts.append(self.setup.qm_method)
        parts.append(self.setup.qm_basis_set)

        if self.setup.dispersion:
            parts.append(self.setup.dispersion)

        if self.setup.additional_keywords:
            parts.append(self.setup.additional_keywords)

        # Job type
        if self.setup.job_type and self.setup.job_type.upper() != "SP":
            parts.append(self.setup.job_type)

        return " ".join(parts)

    def generate_input_content(self, title: str = "") -> str:
        """
        Generate the complete ORCA input file content.

        Args:
            title: Optional title/comment for the file header

        Returns:
            Complete .inp file content as a string
        """
        lines = []

        # Header comment
        lines.append(f"# ORCA QM/MM input file generated by ProPrep")
        if title:
            lines.append(f"# {title}")
        lines.append(f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")

        # Simple input line
        simple_line = self.build_simple_input_line()
        lines.append(f"! {simple_line}")
        lines.append("")

        # Parallelization
        lines.append(f"%pal nprocs {self.setup.n_processors} end")
        lines.append("")

        # Memory per core
        lines.append(f"%maxcore {self.setup.memory_mb}")
        lines.append("")

        # QM/MM block
        lines.append("%qmmm")

        # QM atoms
        if self.setup.use_qm_info_from_pdb:
            lines.append("    Use_QM_InfoFromPDB true")
        else:
            qm_range = compress_indices(self.setup.qm_atom_indices)
            lines.append(f"    QMAtoms {{{qm_range}}} end")

        # Active atoms
        if self.setup.use_active_info_from_pdb:
            lines.append("    Use_Active_InfoFromPDB true")
        else:
            active_range = compress_indices(self.setup.active_atom_indices)
            lines.append(f"    ActiveAtoms {{{active_range}}} end")

        # Force field file
        ff_basename = os.path.basename(self.setup.orca_ff_file)
        lines.append(f'    ORCAFFFilename "{ff_basename}"')

        # Charge and multiplicity for QM region
        lines.append(f"    Charge_Total {self.setup.qm_charge}")
        lines.append(f"    Mult_Total {self.setup.qm_multiplicity}")

        # Embedding
        lines.append(f"    Embedding {self.setup.embedding}")

        # Charge alteration scheme (only relevant for electrostatic embedding)
        if self.setup.embedding == "Electrostatic":
            lines.append(f"    ChargeAlteration {self.setup.charge_scheme}")
            if self.setup.scale_cs is not None and self.setup.charge_scheme == "CS":
                lines.append(f"    Scale_CS {self.setup.scale_cs}")
            if self.setup.scale_rcd is not None and self.setup.charge_scheme == "RCD":
                lines.append(f"    Scale_RCD {self.setup.scale_rcd}")

        # Link atom distance overrides (only if set)
        if self.setup.dist_c_hla is not None:
            lines.append(f"    Dist_C_HLA {self.setup.dist_c_hla}")
        if self.setup.dist_n_hla is not None:
            lines.append(f"    Dist_N_HLA {self.setup.dist_n_hla}")
        if self.setup.dist_o_hla is not None:
            lines.append(f"    Dist_O_HLA {self.setup.dist_o_hla}")

        # Boundary double-counting (only write if changed from default=True)
        if not self.setup.delete_la_double_counting:
            lines.append("    DeleteLADoubleCounting false")
        if not self.setup.delete_la_bond_double_counting:
            lines.append("    DeleteLABondDoubleCounting false")

        # Performance / water
        if self.setup.rigid_mm_water:
            lines.append("    Rigid_MM_Water true")
        if not self.setup.do_nb_fixed_fixed:
            lines.append("    Do_NB_For_Fixed_Fixed false")

        # Print level (only if non-default)
        if self.setup.print_level != 1:
            lines.append(f"    PrintLevel {self.setup.print_level}")

        lines.append("end")
        lines.append("")

        # %mm block (only if any non-default MM settings)
        mm_block = self._generate_mm_block()
        if mm_block:
            lines.append(mm_block)
            lines.append("")

        # Coordinate specification - PDB file
        pdb_basename = os.path.basename(self.setup.pdb_path)
        lines.append(f"* pdbfile {self.setup.qm_charge} {self.setup.qm_multiplicity} {pdb_basename}")
        lines.append("")

        return "\n".join(lines)

    def _generate_mm_block(self) -> Optional[str]:
        """Generate a %mm block if any MM settings differ from ORCA defaults."""
        mm_lines = []

        if self.setup.coulomb_cutoff is not None:
            mm_lines.append(f"    CoulombCutOff {self.setup.coulomb_cutoff}")
        if self.setup.lj_cutoff_inner is not None:
            mm_lines.append(f"    LJCutOffInner {self.setup.lj_cutoff_inner}")
        if self.setup.lj_cutoff_outer is not None:
            mm_lines.append(f"    LJCutOffOuter {self.setup.lj_cutoff_outer}")
        if self.setup.dielec_const is not None:
            mm_lines.append(f"    DielecConst {self.setup.dielec_const}")

        if not mm_lines:
            return None

        return "%mm\n" + "\n".join(mm_lines) + "\nend"

    def write_input_file(self, output_path: str, title: str = "") -> str:
        """
        Write the ORCA .inp file to disk.

        Args:
            output_path: Path for the output .inp file
            title: Optional title for file header

        Returns:
            Path to the written file
        """
        content = self.generate_input_content(title=title)
        with open(output_path, 'w') as f:
            f.write(content)
        return output_path

    def prepare_pdb_file(self, output_path: str, rst7_path: str = "") -> str:
        """
        Write a PDB file with occupancy and B-factor columns set for ORCA QM/MM.

        - Occupancy = 1.0 for QM atoms, 0.0 for MM atoms
        - B-factor = 1.0 for active atoms, 0.0 for frozen atoms

        This allows ORCA to identify QM and active regions from the PDB itself.

        Args:
            output_path: Path for the output PDB file
            rst7_path: Optional override for coordinate file (for multi-frame mode)

        Returns:
            Path to the written PDB file
        """
        coords = rst7_path if rst7_path else self.setup.rst7_path
        parm = parmed.load_file(self.setup.prmtop_path, coords)

        qm_set = set(self.setup.qm_atom_indices)
        active_set = set(self.setup.active_atom_indices)

        for i, atom in enumerate(parm.atoms):
            atom.occupancy = 1.0 if i in qm_set else 0.0
            atom.bfactor = 1.0 if i in active_set else 0.0

        parm.save(output_path, overwrite=True)
        return output_path

    def write_run_script(self, output_path: str, inp_filename: str,
                         orca_dir: str = "") -> str:
        """
        Write a convenience shell script for running the ORCA calculation.

        Args:
            output_path: Path for the shell script
            inp_filename: Name of the .inp file (not full path)
            orca_dir: Path to the ORCA installation directory

        Returns:
            Path to the written script
        """
        stem = Path(inp_filename).stem
        script_name = os.path.basename(output_path)
        orca_bin = os.path.join(orca_dir, "orca") if orca_dir else "orca"
        nprocs = self.setup.n_processors

        content = f"""#!/bin/bash
# ORCA QM/MM run script generated by ProPrep
# Usage: ./{script_name}
#   or:  nohup ./{script_name} &
#
# Input:  {inp_filename}
# Output: {stem}.out
# Procs:  {nprocs}

set -euo pipefail

# --- ORCA environment ---
ORCA_DIR="{orca_dir}"
export PATH="$ORCA_DIR:$PATH"
export LD_LIBRARY_PATH="${{LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}}$ORCA_DIR"

ORCA_BIN="{orca_bin}"
INP="{inp_filename}"
OUT="{stem}.out"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

cd "$SCRIPT_DIR"

# --- Preflight checks ---
if [[ ! -x "$ORCA_BIN" ]]; then
    echo "ERROR: ORCA binary not found or not executable: $ORCA_BIN" >&2
    exit 1
fi

for f in "$INP" "{os.path.basename(self.setup.orca_ff_file)}" "{os.path.basename(self.setup.pdb_path)}"; do
    if [[ ! -f "$f" ]]; then
        echo "ERROR: Required file missing: $f" >&2
        exit 1
    fi
done

# --- Run ---
echo "======================================"
echo " ORCA QM/MM Calculation"
echo "======================================"
echo " Input:   $INP"
echo " Output:  $OUT"
echo " Procs:   {nprocs}"
echo " Started: $(date)"
echo "======================================"
echo ""

nohup "$ORCA_BIN" "$INP" > "$OUT" 2>&1 &
ORCA_PID=$!
echo "ORCA running in background (PID: $ORCA_PID)"
echo "$ORCA_PID" > {stem}.pid

# Wait for completion
wait $ORCA_PID
EXIT_CODE=$?
rm -f {stem}.pid

echo ""
echo "======================================"
if [[ $EXIT_CODE -eq 0 ]]; then
    echo " Calculation finished successfully."
else
    echo " Calculation FAILED (exit code: $EXIT_CODE)"
fi
echo " Ended:   $(date)"
echo " Output:  $OUT"
echo "======================================"

# Quick summary from output
if [[ -f "$OUT" ]]; then
    if grep -q "FINAL SINGLE POINT ENERGY" "$OUT"; then
        echo ""
        grep "FINAL SINGLE POINT ENERGY" "$OUT" | tail -1
    fi
    if grep -q "HURRAY" "$OUT"; then
        echo "Geometry optimization converged."
    fi
fi

exit $EXIT_CODE
"""
        with open(output_path, 'w') as f:
            f.write(content)
        os.chmod(output_path, 0o755)
        return output_path
