"""
AMBER MDIN Configuration Interface - Layer 1: MDIN Writer

Generates valid MDIN text from structured data with optional commenting
and organization features.

Usage:
    from proprep.md_prep.amber import MdinWriter, write_mdin

    # Simple usage
    data = {
        "cntrl": {
            "imin": 0,
            "nstlim": 500000,
            "dt": 0.002,
            "ntt": 3,
            "gamma_ln": 1.0,
        }
    }
    text = write_mdin(data, title="Production MD")

    # With more control
    writer = MdinWriter()
    text = writer.write(data, comments=True, group_by_category=True)
"""

import logging
from typing import Any

from .keyword_db import KeywordDB, get_keyword_db

logger = logging.getLogger(__name__)


class MdinWriter:
    """
    Generates valid MDIN text from structured data.

    Features:
    - Automatic value formatting (bool -> .true./.false., strings -> quoted)
    - Optional comments from keyword database descriptions
    - Optional grouping by category within sections
    - Configurable line width
    """

    def __init__(self, db: KeywordDB | None = None):
        """
        Initialize the writer.

        Args:
            db: KeywordDB instance for metadata. Defaults to singleton.
        """
        self.db = db if db is not None else get_keyword_db()

    def write(
        self,
        sections: dict[str, dict[str, Any]],
        title: str = "AMBER MD input generated by ProPrep",
        comments: bool = True,
        comment_style: str = "inline",
        group_by_category: bool = True,
        include_defaults: bool = False,
        max_line_width: int = 80,
    ) -> str:
        """
        Generate MDIN text from section data.

        Args:
            sections: Dict mapping section names to {keyword: value} dicts.
                     e.g., {"cntrl": {"imin": 0, "nstlim": 500000}}
            title: Title line(s) at the start of the file
            comments: Include keyword descriptions as comments
            comment_style: "inline" (after value) or "above" (separate line)
            group_by_category: Organize keywords by category within sections
            include_defaults: Include keywords at their default values
            max_line_width: Target maximum line width

        Returns:
            Formatted MDIN text string
        """
        lines: list[str] = []

        # Title
        lines.append(title)

        # Process each section
        for section_name, section_data in sections.items():
            if not section_data:
                continue

            section_lines = self._write_section(
                section_name,
                section_data,
                comments=comments,
                comment_style=comment_style,
                group_by_category=group_by_category,
                include_defaults=include_defaults,
                max_line_width=max_line_width,
            )
            lines.extend(section_lines)

        return "\n".join(lines) + "\n"

    def _write_section(
        self,
        section_name: str,
        section_data: dict[str, Any],
        comments: bool,
        comment_style: str,
        group_by_category: bool,
        include_defaults: bool,
        max_line_width: int,
    ) -> list[str]:
        """Write a single namelist section."""
        lines: list[str] = []

        # Section header
        lines.append(f" &{section_name}")

        if group_by_category:
            lines.extend(
                self._write_grouped_entries(
                    section_name,
                    section_data,
                    comments,
                    comment_style,
                    include_defaults,
                    max_line_width,
                )
            )
        else:
            lines.extend(
                self._write_flat_entries(
                    section_name,
                    section_data,
                    comments,
                    comment_style,
                    include_defaults,
                    max_line_width,
                )
            )

        # Section terminator
        lines.append(" /")

        return lines

    def _write_grouped_entries(
        self,
        section_name: str,
        section_data: dict[str, Any],
        comments: bool,
        comment_style: str,
        include_defaults: bool,
        max_line_width: int,
    ) -> list[str]:
        """Write entries grouped by category."""
        lines: list[str] = []

        # Get all keywords in this section
        section_keywords = {kw.name.lower(): kw for kw in self.db.by_section(section_name)}

        # Group entries by category
        categorized: dict[str, list[tuple[str, Any]]] = {}
        uncategorized: list[tuple[str, Any]] = []

        for key, value in section_data.items():
            key_lower = key.lower()
            kw = section_keywords.get(key_lower)

            if kw and kw.category:
                if kw.category not in categorized:
                    categorized[kw.category] = []
                categorized[kw.category].append((key, value))
            else:
                uncategorized.append((key, value))

        # Sort categories by order of first appearance in database
        category_order = self.db.categories(section_name)
        sorted_categories = sorted(
            categorized.keys(),
            key=lambda c: category_order.index(c) if c in category_order else len(category_order),
        )

        # Write each category
        first_category = True
        for category in sorted_categories:
            entries = categorized[category]
            if not entries:
                continue

            # Category header comment
            if comments:
                if not first_category:
                    lines.append("")
                short_cat = self._truncate_category(category, max_line_width - 10)
                lines.append(f"   ! --- {short_cat} ---")
            first_category = False

            # Write entries
            for key, value in entries:
                entry_lines = self._format_entry(
                    key,
                    value,
                    section_name,
                    comments,
                    comment_style,
                    include_defaults,
                    max_line_width,
                )
                lines.extend(entry_lines)

        # Write uncategorized entries
        if uncategorized:
            if comments and categorized:
                lines.append("")
                lines.append("   ! --- Other ---")
            for key, value in uncategorized:
                entry_lines = self._format_entry(
                    key,
                    value,
                    section_name,
                    comments,
                    comment_style,
                    include_defaults,
                    max_line_width,
                )
                lines.extend(entry_lines)

        return lines

    def _write_flat_entries(
        self,
        section_name: str,
        section_data: dict[str, Any],
        comments: bool,
        comment_style: str,
        include_defaults: bool,
        max_line_width: int,
    ) -> list[str]:
        """Write entries without category grouping."""
        lines: list[str] = []

        for key, value in section_data.items():
            entry_lines = self._format_entry(
                key,
                value,
                section_name,
                comments,
                comment_style,
                include_defaults,
                max_line_width,
            )
            lines.extend(entry_lines)

        return lines

    def _format_entry(
        self,
        key: str,
        value: Any,
        section_name: str,
        comments: bool,
        comment_style: str,
        include_defaults: bool,
        max_line_width: int,
    ) -> list[str]:
        """Format a single key=value entry."""
        lines: list[str] = []

        # Look up keyword metadata
        kw = self.db.get(key, section_name)

        # Check if at default (skip if not including defaults)
        if not include_defaults and kw and kw.default is not None:
            if value == kw.default:
                return []

        # Format the value
        formatted_value = self._format_value(value, kw)

        # Build the entry line
        entry = f"   {key}={formatted_value},"

        # Add comment if requested
        if comments and kw:
            comment = self._make_comment(kw, max_line_width - len(entry) - 3)

            if comment_style == "above":
                lines.append(f"   ! {comment}")
                lines.append(entry)
            else:  # inline
                if len(entry) + len(comment) + 4 <= max_line_width:
                    lines.append(f"{entry}  ! {comment}")
                else:
                    # Comment too long for inline, put above
                    lines.append(f"   ! {comment}")
                    lines.append(entry)
        else:
            lines.append(entry)

        return lines

    def _format_value(self, value: Any, kw: Any | None = None) -> str:
        """
        Format a Python value for MDIN output.

        Args:
            value: Python value to format
            kw: Optional Keyword for type hints

        Returns:
            Formatted string for MDIN
        """
        if value is None:
            return ""

        if isinstance(value, bool):
            return ".true." if value else ".false."

        if isinstance(value, int):
            return str(value)

        if isinstance(value, float):
            # Use :g format but ensure at least one decimal for clarity
            formatted = f"{value:g}"
            if "." not in formatted and "e" not in formatted.lower():
                formatted = f"{int(value)}.0"
            return formatted

        if isinstance(value, str):
            # Quote strings
            # Escape any internal single quotes
            escaped = value.replace("'", "''")
            return f"'{escaped}'"

        if isinstance(value, (list, tuple)):
            # Format each element
            return ",".join(self._format_value(v, kw) for v in value)

        # Fallback: convert to string
        return str(value)

    def _make_comment(self, kw: Any, max_len: int) -> str:
        """Create a short comment from keyword description."""
        # Start with a short summary
        desc = kw.description or ""

        # Take first sentence or truncate
        if "." in desc:
            first_sentence = desc.split(".")[0]
        else:
            first_sentence = desc

        # Clean up and truncate
        comment = " ".join(first_sentence.split())
        if len(comment) > max_len:
            comment = comment[: max_len - 3].rsplit(" ", 1)[0] + "..."

        return comment

    def _truncate_category(self, category: str, max_len: int) -> str:
        """Truncate category name if too long."""
        if len(category) <= max_len:
            return category
        return category[: max_len - 3] + "..."

    def write_file(self, path: str, sections: dict[str, dict[str, Any]], **kwargs) -> None:
        """
        Write MDIN to a file.

        Args:
            path: Output file path
            sections: Section data (same as write())
            **kwargs: Additional arguments passed to write()
        """
        text = self.write(sections, **kwargs)
        with open(path, "w") as f:
            f.write(text)


# =============================================================================
# Convenience function
# =============================================================================


def write_mdin(
    sections: dict[str, dict[str, Any]],
    title: str = "AMBER MD input generated by ProPrep",
    comments: bool = True,
    comment_style: str = "inline",
    group_by_category: bool = True,
    include_defaults: bool = False,
    max_line_width: int = 80,
) -> str:
    """
    Generate MDIN text from section data.

    Convenience function that creates a writer and calls write().

    Args:
        sections: Dict mapping section names to {keyword: value} dicts.
        title: Title line(s) at the start of the file
        comments: Include keyword descriptions as comments
        comment_style: "inline" (after value) or "above" (separate line)
        group_by_category: Organize keywords by category within sections
        include_defaults: Include keywords at their default values
        max_line_width: Target maximum line width

    Returns:
        Formatted MDIN text string
    """
    writer = MdinWriter()
    return writer.write(
        sections,
        title=title,
        comments=comments,
        comment_style=comment_style,
        group_by_category=group_by_category,
        include_defaults=include_defaults,
        max_line_width=max_line_width,
    )
