"""
AMBER MDIN Configuration Interface - Layer 3: Interactive Builder

A terminal-based interactive builder for AMBER MDIN files. Users can browse
keywords by section and category, configure values, validate in real-time,
and generate well-documented MDIN files.

Usage:
    from proprep.md_prep.amber import MdinBuilder

    # Interactive mode
    builder = MdinBuilder()
    builder.run()

    # Programmatic mode
    builder = MdinBuilder()
    builder.set("imin", 0)
    builder.set("nstlim", 500000)
    builder.set("dt", 0.002)
    result = builder.validate()
    builder.write("production.mdin")
"""

import logging
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text
from rich.syntax import Syntax
from rich.columns import Columns
from rich.prompt import Prompt, Confirm, IntPrompt, FloatPrompt

from .keyword_db import KeywordDB, get_keyword_db, Keyword
from .mdin_writer import MdinWriter
from .mdin_validator import MdinValidator, ValidationResult, Severity

logger = logging.getLogger(__name__)


# =============================================================================
# Builder State
# =============================================================================


@dataclass
class BuilderState:
    """
    The state of an MDIN file being constructed.

    Tracks all configured values and provides methods for manipulation.
    """

    title: str = "AMBER MD input generated by ProPrep"
    entries: dict[str, dict[str, Any]] = field(default_factory=dict)
    # entries["cntrl"]["nstlim"] = 500000, etc.

    def set(self, key: str, value: Any, section: str = "cntrl") -> None:
        """Set a keyword value."""
        if section not in self.entries:
            self.entries[section] = {}
        self.entries[section][key.lower()] = value

    def unset(self, key: str, section: str = "cntrl") -> None:
        """Remove a keyword value."""
        if section in self.entries:
            self.entries[section].pop(key.lower(), None)
            # Remove empty sections
            if not self.entries[section]:
                del self.entries[section]

    def get(self, key: str, section: str = "cntrl") -> Any | None:
        """Get a keyword value."""
        return self.entries.get(section, {}).get(key.lower())

    def has(self, key: str, section: str = "cntrl") -> bool:
        """Check if a keyword is set."""
        return key.lower() in self.entries.get(section, {})

    def active_sections(self) -> list[str]:
        """Get sections that have values set."""
        return [s for s, e in self.entries.items() if e]

    def count_in_section(self, section: str) -> int:
        """Count keywords set in a section."""
        return len(self.entries.get(section, {}))

    def count_in_category(self, section: str, category: str, db: KeywordDB) -> int:
        """Count keywords set in a category."""
        count = 0
        for kw in db.by_category(category):
            if kw.section.lower() == section.lower():
                if self.has(kw.name, section):
                    count += 1
        return count

    def all_entries(self) -> list[tuple[str, str, Any]]:
        """Get all (section, key, value) tuples."""
        result = []
        for section, entries in self.entries.items():
            for key, value in entries.items():
                result.append((section, key, value))
        return result

    def clear(self) -> None:
        """Clear all entries."""
        self.entries.clear()

    def copy(self) -> "BuilderState":
        """Create a copy of this state."""
        new_state = BuilderState(title=self.title)
        for section, entries in self.entries.items():
            new_state.entries[section] = dict(entries)
        return new_state


# =============================================================================
# Category Relevance Rules
# =============================================================================

# These rules determine which categories are "relevant" based on current state.
# Irrelevant categories are shown dimmed but still accessible.

# Category sort order following AMBER manual structure (§22.6.x)
# Lower numbers appear first; categories not listed sort to the end alphabetically
CATEGORY_ORDER: dict[str, int] = {
    # Core setup (§22.6.1-4)
    "General flags describing the calculation": 1,
    "Nature and format of the input": 2,
    "Nature and format of the output": 3,
    "Frozen or restrained atoms": 4,
    # Run types (§22.6.5-6)
    "Energy minimization": 5,
    "Molecular dynamics": 6,
    # Dynamics controls (§22.6.7-10)
    "Temperature regulation": 7,
    "Pressure regulation": 8,
    "SHAKE bond length constraints": 9,
    "Middle scheme": 10,
    # Potential function (§22.6.11)
    "Potential function - generic parameters": 11,
    "Potential function - MC water": 12,
    "Potential function - RAMD": 13,
    "Potential function - TI decomposition": 14,
    # Solvation models (§22.6.12-13)
    "Generalized Born": 15,
    "Generalized Born - ALPB": 16,
    "Generalized Born - GBION": 17,
    "Generalized Born - GTFE": 18,
    "Generalized Born - igb8 parameters": 19,
    "Poisson-Boltzmann": 20,
    # Specialized features (§22.6.14+)
    "NMR refinement options": 21,
    "EMAP restraints": 22,
    "Isotropic Periodic Sum": 23,
    "Water cap": 24,
    "PMEMD-specific": 25,
    # Later chapters
    "Constant pH MD": 26,
    "Constant Redox Potential MD": 27,
    "Continuous Constant pH MD": 28,
}

CATEGORY_RELEVANCE: dict[str, callable] = {
    # Note: s.get() returns None if not set, so use "or 0" for numeric defaults
    "Energy minimization": lambda s: s.get("imin") == 1,
    "Molecular dynamics": lambda s: (s.get("imin") or 0) == 0,  # Default is MD (imin=0)
    "Temperature regulation": lambda s: (s.get("imin") or 0) == 0,
    "Pressure regulation": lambda s: (s.get("imin") or 0) == 0,
    "Generalized Born": lambda s: (s.get("igb") or 0) > 0,
    "Poisson-Boltzmann": lambda s: (s.get("ipb") or 0) > 0,
    "Constant pH MD": lambda s: (s.get("icnstph") or 0) > 0,
    "Constant Redox Potential MD": lambda s: (s.get("icnste") or 0) > 0,
    "Continuous Constant pH MD": lambda s: (s.get("iphmd") or 0) > 0,
    "SHAKE bond length constraints": lambda s: (s.get("imin") or 0) == 0,
    "Water cap": lambda s: (s.get("ivcap") or 0) > 0,
    "NMR refinement options": lambda s: (s.get("nmropt") or 0) > 0,
    "EMAP restraints": lambda s: (s.get("iemap") or 0) > 0,
}

# Section relevance rules - which &cntrl keywords enable other sections
SECTION_TRIGGERS: dict[str, tuple[str, callable]] = {
    # section: (description, condition)
    "ewald": ("ntb > 0", lambda s: (s.get("ntb") or 0) > 0),
    "pb": ("ipb > 0", lambda s: (s.get("ipb") or 0) > 0),
    "qmmm": ("ifqnt = 1", lambda s: s.get("ifqnt") == 1),
    # QM interface sections - depend on ifqnt and qm_theory
    "gau": ("ifqnt=1", lambda s: s.get("ifqnt") == 1),
    "orc": ("ifqnt=1", lambda s: s.get("ifqnt") == 1),
    "tc": ("ifqnt=1", lambda s: s.get("ifqnt") == 1),
    "adf": ("ifqnt=1", lambda s: s.get("ifqnt") == 1),
    "gms": ("ifqnt=1", lambda s: s.get("ifqnt") == 1),
    "quick": ("ifqnt=1", lambda s: s.get("ifqnt") == 1),
    "dftbplus": ("ifqnt=1", lambda s: s.get("ifqnt") == 1),
    "xtb": ("ifqnt=1", lambda s: s.get("ifqnt") == 1),
    "sebomd": ("ifqnt=1", lambda s: s.get("ifqnt") == 1),
    "mrcc": ("ifqnt=1", lambda s: s.get("ifqnt") == 1),
    "qc": ("ifqnt=1", lambda s: s.get("ifqnt") == 1),
    "adqmmm": ("ifqnt=1", lambda s: s.get("ifqnt") == 1),
    # Constant pH sections
    "phmdin": ("icnstph > 0", lambda s: (s.get("icnstph") or 0) > 0),
    "phmdparm": ("icnstph > 0", lambda s: (s.get("icnstph") or 0) > 0),
    "phmdstrt": ("icnstph > 0", lambda s: (s.get("icnstph") or 0) > 0),
    # Other specialized sections
    "debugf": ("optional", lambda s: False),  # No trigger - always parsed if present, access via Search
    "fb": ("ifqnt=1, qm_theory=EXTERN", lambda s: s.get("ifqnt") == 1),  # External QM interface
    "dprc": ("ifqnt=1", lambda s: s.get("ifqnt") == 1),  # DPRc correction alongside &qmmm
    "pol_gauss": ("ipgm=1", lambda s: s.get("ipgm") == 1),  # pGM force field
    "vsolv": ("ifqnt=1, vsolv in &qmmm", lambda s: s.get("ifqnt") == 1),  # Adaptive solvent QM/MM
}


# =============================================================================
# Interactive Builder
# =============================================================================


class MdinBuilder:
    """
    Interactive MDIN file builder.

    Provides both a TUI interface and programmatic API for building
    AMBER MDIN configuration files.
    """

    def __init__(
        self,
        db: KeywordDB | None = None,
        console: Console | None = None,
        state: BuilderState | None = None,
    ):
        """
        Initialize the builder.

        Args:
            db: KeywordDB instance. Defaults to singleton.
            console: Rich console for output. Defaults to new Console.
            state: Initial state. Defaults to empty BuilderState.
        """
        self.db = db if db is not None else get_keyword_db()
        self.console = console if console is not None else Console()
        self.state = state if state is not None else BuilderState()
        self.writer = MdinWriter(self.db)
        self.validator = MdinValidator(self.db)

        # Navigation stack for back functionality
        self._nav_stack: list[str] = []

    # -------------------------------------------------------------------------
    # Text Formatting Helpers
    # -------------------------------------------------------------------------

    def _wrap_text(self, text: str, indent: int = 2, width: int = 76) -> str:
        """
        Wrap text with consistent indentation on all lines.

        Args:
            text: Text to wrap
            indent: Number of spaces to indent each line
            width: Maximum line width

        Returns:
            Wrapped text with consistent indentation
        """
        prefix = " " * indent
        wrapped = textwrap.fill(
            text,
            width=width,
            initial_indent=prefix,
            subsequent_indent=prefix,
        )
        return wrapped

    # -------------------------------------------------------------------------
    # Programmatic API
    # -------------------------------------------------------------------------

    def set(self, key: str, value: Any, section: str = "cntrl") -> "MdinBuilder":
        """
        Set a keyword value.

        Args:
            key: Keyword name
            value: Value to set
            section: Namelist section (default: cntrl)

        Returns:
            self for method chaining
        """
        self.state.set(key, value, section)
        return self

    def unset(self, key: str, section: str = "cntrl") -> "MdinBuilder":
        """Remove a keyword value."""
        self.state.unset(key, section)
        return self

    def get(self, key: str, section: str = "cntrl") -> Any | None:
        """Get a keyword value."""
        return self.state.get(key, section)

    def validate(self) -> ValidationResult:
        """
        Validate the current configuration.

        Returns:
            ValidationResult with any issues found
        """
        # Generate MDIN text and validate
        from .mdin_parser import parse_mdin

        text = self.writer.write(self.state.entries, title=self.state.title, comments=False)
        parsed = parse_mdin(text)
        return self.validator.validate(parsed)

    def preview(self, comments: bool = True) -> str:
        """
        Generate preview of the MDIN file.

        Args:
            comments: Include comments from keyword descriptions

        Returns:
            Formatted MDIN text
        """
        return self.writer.write(
            self.state.entries,
            title=self.state.title,
            comments=comments,
            group_by_category=True,
        )

    def write(self, path: str | Path, comments: bool = True) -> None:
        """
        Write the MDIN file to disk.

        Args:
            path: Output file path
            comments: Include comments from keyword descriptions
        """
        text = self.preview(comments=comments)
        Path(path).write_text(text)
        self.console.print(f"[green]Wrote MDIN file to {path}[/green]")

    # -------------------------------------------------------------------------
    # Interactive TUI
    # -------------------------------------------------------------------------

    def run(self) -> None:
        """
        Run the interactive builder TUI.

        Main entry point for interactive use.
        """
        self.console.clear()
        self._show_header()

        while True:
            action = self._main_menu()
            if action == "quit":
                break

    def _show_header(self) -> None:
        """Show the builder header."""
        self.console.print()
        self.console.print(
            Panel(
                "[bold cyan]AMBER MDIN Builder[/bold cyan]\n"
                "[grey50]Interactive configuration file generator[/grey50]",
                border_style="cyan",
            )
        )

    def _main_menu(self) -> str:
        """
        Show the main menu.

        Returns:
            Action to take ("quit" to exit)
        """
        self.console.print()

        # Build menu options
        table = Table(show_header=False, box=None, padding=(0, 2))
        table.add_column("Key", style="cyan bold")
        table.add_column("Action")
        table.add_column("Status", style="grey50")

        # Always show &cntrl first
        cntrl_count = self.state.count_in_section("cntrl")
        cntrl_status = f"[green]{cntrl_count} set[/green]" if cntrl_count > 0 else ""
        table.add_row("C", "&cntrl", cntrl_status)

        # Dynamically show sections that are triggered by &cntrl settings
        # Map key -> section for choice handling
        key_to_section: dict[str, str] = {"c": "cntrl"}
        used_keys = {"c", "s", "p", "v", "w", "t", "q"}  # Reserved keys

        for section, (desc, condition) in SECTION_TRIGGERS.items():
            if section in self.db.sections():
                try:
                    if condition(self.state):
                        count = self.state.count_in_section(section)
                        status = f"[green]{count} set[/green]" if count > 0 else ""
                        # Find an available key
                        key = section[0].lower()
                        if key in used_keys:
                            key = section[:2].lower()
                        if key in used_keys:
                            # Skip if we can't find a unique key
                            continue
                        used_keys.add(key)
                        key_to_section[key] = section
                        table.add_row(key.upper(), f"&{section}", status)
                except Exception:
                    pass

        table.add_row("", "", "")
        table.add_row("S", "[bold]Search[/bold] keywords", "")
        table.add_row("P", "[bold]Preview[/bold] MDIN", "")
        table.add_row("V", "[bold]Validate[/bold] configuration", "")
        table.add_row("W", "[bold]Write[/bold] to file", "")
        table.add_row("T", "Edit [bold]title[/bold]", "")
        table.add_row("", "", "")
        table.add_row("Q", "Quit", "")

        self.console.print(table)

        # Show note about other sections if only &cntrl is available
        if len(key_to_section) == 1:
            self.console.print(
                "\n[italic]Other namelist sections (&ewald, &pb, &qmmm, etc.) will appear "
                "here when you enable their corresponding &cntrl keywords.[/italic]"
            )

        # Show validation summary if there are issues
        result = self.validate()
        if result.errors:
            self.console.print(f"\n[red]⚠ {len(result.errors)} validation error(s):[/red]")
            for issue in result.errors[:3]:  # Show first 3
                self.console.print(f"  [red]• {issue.message}[/red]")
            if len(result.errors) > 3:
                self.console.print(f"  [red]  ... and {len(result.errors) - 3} more[/red]")
        elif result.warnings:
            self.console.print(f"\n[yellow]⚠ {len(result.warnings)} warning(s):[/yellow]")
            for issue in result.warnings[:3]:  # Show first 3
                self.console.print(f"  [yellow]• {issue.message}[/yellow]")
            if len(result.warnings) > 3:
                self.console.print(f"  [yellow]  ... and {len(result.warnings) - 3} more (press V for details)[/yellow]")

        # Build valid choices list (include both upper and lowercase)
        base_choices = list(key_to_section.keys()) + ["s", "p", "v", "w", "t", "q", "quit"]
        all_choices = base_choices + [c.upper() for c in base_choices if len(c) == 1]

        # Get choice
        choice = Prompt.ask(
            "\nSelect",
            choices=all_choices,
            default="c",
            show_choices=False,
        ).lower()

        if choice in ["q", "quit"]:
            return "quit"
        elif choice in key_to_section:
            self._browse_section(key_to_section[choice])
        elif choice == "s":
            self._search_keywords()
        elif choice == "p":
            self._show_preview()
        elif choice == "v":
            self._show_validation()
        elif choice == "w":
            self._write_file()
        elif choice == "t":
            self._edit_title()

        return "continue"

    def _browse_section(self, section: str) -> None:
        """Browse categories within a section."""
        while True:
            self.console.print()
            self.console.print(
                f"[bold cyan]&{section}[/bold cyan] — Select a category:"
            )
            self.console.print()

            # Get categories in this section
            categories = self.db.categories(section)
            if not categories:
                self.console.print("[grey50]No categories in this section[/grey50]")
                Prompt.ask("Press Enter to go back")
                return

            # Build category table
            table = Table(show_header=False, box=None, padding=(0, 2))
            table.add_column("Key", style="cyan", width=4)
            table.add_column("Category")
            table.add_column("Status", style="grey50")

            # Sort categories by manual order (CATEGORY_ORDER)
            def category_sort_key(cat: str) -> tuple:
                order = CATEGORY_ORDER.get(cat, 999)
                return (order, cat.lower())

            sorted_cats = sorted(categories, key=category_sort_key)

            for i, category in enumerate(sorted_cats):
                count = self.state.count_in_category(section, category, self.db)

                # Format status
                if count > 0:
                    status = f"[green]{count} set[/green]"
                else:
                    status = ""

                table.add_row(str(i + 1), category, status)

            table.add_row("", "", "")
            table.add_row("B", "[grey50]Back[/grey50]", "")

            self.console.print(table)

            # Get choice (accept both upper and lowercase)
            choices = [str(i + 1) for i in range(len(sorted_cats))] + ["b", "B", "back"]
            choice = Prompt.ask(
                "Select category",
                choices=choices,
                default="b",
                show_choices=False,
            ).lower()

            if choice in ["b", "back"]:
                return

            try:
                idx = int(choice) - 1
                if 0 <= idx < len(sorted_cats):
                    self._browse_category(section, sorted_cats[idx])
            except ValueError:
                pass

    def _browse_category(self, section: str, category: str) -> None:
        """Browse keywords within a category."""
        while True:
            self.console.print()
            self.console.print(
                f"[bold cyan]&{section}[/bold cyan] → [cyan]{category}[/cyan]"
            )
            self.console.print()

            # Get keywords in this category and section
            keywords = [
                kw
                for kw in self.db.by_category(category)
                if kw.section.lower() == section.lower()
            ]

            if not keywords:
                self.console.print("[grey50]No keywords in this category[/grey50]")
                Prompt.ask("Press Enter to go back")
                return

            # Sort: commonly_changed first, then set values, then alphabetical
            def keyword_sort_key(kw: Keyword) -> tuple:
                is_set = self.state.has(kw.name, section)
                return (not kw.commonly_changed, not is_set, kw.name.lower())

            sorted_keywords = sorted(keywords, key=keyword_sort_key)

            # Build keyword table
            table = Table(show_header=False, box=None, padding=(0, 1))
            table.add_column("Key", style="cyan", width=4)
            table.add_column("Keyword")  # No fixed width - let it expand
            table.add_column("Value", width=12)
            table.add_column("Description")

            for i, kw in enumerate(sorted_keywords):
                current_value = self.state.get(kw.name, section)
                is_set = current_value is not None

                # Format markers
                markers = ""
                if kw.commonly_changed:
                    markers += "▸"
                if is_set:
                    markers += "✓"

                # Format keyword name
                if is_set:
                    kw_text = f"[green]{kw.name}[/green]"
                elif kw.commonly_changed:
                    kw_text = f"[bold]{kw.name}[/bold]"
                else:
                    kw_text = kw.name

                # Format value
                if is_set:
                    val_text = f"[green]{current_value}[/green]"
                elif kw.default is not None:
                    val_text = f"[grey50]({kw.default})[/grey50]"
                else:
                    val_text = ""

                # Full description - no truncation
                desc = kw.description or ""

                table.add_row(str(i + 1), f"{markers} {kw_text}", val_text, desc)

            table.add_row("", "", "", "")
            table.add_row("B", "[grey50]Back[/grey50]", "", "")

            self.console.print(table)
            self.console.print()
            self.console.print("[grey50]▸ = commonly changed    ✓ = currently set[/grey50]")

            # Get choice (accept both upper and lowercase)
            choices = [str(i + 1) for i in range(len(sorted_keywords))] + ["b", "B", "back"]
            choice = Prompt.ask(
                "Select keyword",
                choices=choices,
                default="b",
                show_choices=False,
            ).lower()

            if choice in ["b", "back"]:
                return

            try:
                idx = int(choice) - 1
                if 0 <= idx < len(sorted_keywords):
                    self._edit_keyword(sorted_keywords[idx])
            except ValueError:
                pass

    def _edit_keyword(self, kw: Keyword) -> None:
        """Edit a single keyword."""
        while True:
            self.console.print()
            self.console.print(f"[bold cyan]{kw.name}[/bold cyan] — {kw.category}")
            self.console.print()

            # Description
            self.console.print("[bold]Description:[/bold]")
            wrapped_desc = self._wrap_text(kw.description or "", indent=2, width=76)
            self.console.print(wrapped_desc)
            self.console.print()

            # Options
            if kw.options:
                self.console.print("[bold]Options:[/bold]")
                current_value = self.state.get(kw.name, kw.section)
                for opt_val, opt_desc in kw.options.items():
                    marker = "▸" if opt_val == current_value else " "
                    # First line with option value
                    self.console.print(f"  {marker} [cyan]{opt_val}[/cyan] — ", end="")
                    # Wrap description with proper indentation for continuation lines
                    # Account for "  X N — " prefix (about 8 chars + len of opt_val)
                    prefix_len = 8 + len(str(opt_val))
                    if len(opt_desc) + prefix_len <= 76:
                        self.console.print(opt_desc)
                    else:
                        # Split into first line and wrapped remainder
                        first_line_width = 76 - prefix_len
                        # Find a good break point
                        if len(opt_desc) <= first_line_width:
                            self.console.print(opt_desc)
                        else:
                            # Wrap the entire description with hanging indent
                            wrapped = textwrap.fill(
                                opt_desc,
                                width=76,
                                initial_indent="",
                                subsequent_indent=" " * prefix_len,
                            )
                            self.console.print(wrapped)
                self.console.print()

            # Current value and default
            current = self.state.get(kw.name, kw.section)
            current_display = current if current is not None else "[italic]not set[/italic]"
            self.console.print(f"[bold]Current value:[/bold] {current_display}")
            self.console.print(f"[bold]Default:[/bold] {kw.default}")

            # Range info
            if kw.min_val is not None or kw.max_val is not None:
                range_str = ""
                if kw.min_val is not None:
                    range_str += f"min: {kw.min_val}"
                if kw.max_val is not None:
                    if range_str:
                        range_str += ", "
                    range_str += f"max: {kw.max_val}"
                self.console.print(f"[bold]Range:[/bold] {range_str}")

            # Notes
            if kw.notes:
                self.console.print()
                self.console.print("[bold]Notes:[/bold]")
                # Wrap notes with consistent indentation
                wrapped_notes = self._wrap_text(kw.notes, indent=2, width=76)
                self.console.print(f"[italic]{wrapped_notes}[/italic]")

            # Related keywords
            if kw.related:
                self.console.print()
                self.console.print(f"[bold]Related:[/bold] {', '.join(kw.related)}")

            self.console.print()

            # Action menu
            table = Table(show_header=False, box=None, padding=(0, 2))
            table.add_column("Key", style="cyan")
            table.add_column("Action")
            table.add_row("E", "Enter new value")
            table.add_row("D", "Use default")
            table.add_row("U", "Unset (remove)")
            if kw.related:
                table.add_row("R", "Jump to related keyword")
            table.add_row("B", "Back")

            self.console.print(table)

            # Accept both upper and lowercase
            base_choices = ["e", "d", "u", "b", "back"]
            if kw.related:
                base_choices.append("r")
            choices = base_choices + [c.upper() for c in base_choices if len(c) == 1]

            choice = Prompt.ask("Action", choices=choices, default="b", show_choices=False).lower()

            if choice in ["b", "back"]:
                return
            elif choice == "e":
                self._enter_value(kw)
            elif choice == "d":
                if kw.default is not None:
                    self.state.set(kw.name, kw.default, kw.section)
                    self.console.print(f"[green]Set {kw.name} = {kw.default}[/green]")
                else:
                    self.console.print("[yellow]No default value defined[/yellow]")
            elif choice == "u":
                self.state.unset(kw.name, kw.section)
                self.console.print(f"[yellow]Unset {kw.name}[/yellow]")
            elif choice == "r" and kw.related:
                self._jump_to_related(kw)
                return  # After jumping to related, exit this keyword's loop

    def _enter_value(self, kw: Keyword) -> None:
        """Prompt user to enter a value for a keyword."""
        # Determine input method based on type and options
        if kw.options:
            # Show options and let user pick
            opt_keys = list(kw.options.keys())
            choices = [str(k) for k in opt_keys]

            self.console.print("\nEnter one of:", ", ".join(choices))
            value_str = Prompt.ask(
                f"Value for {kw.name}",
                default=str(kw.default) if kw.default is not None else None,
            )

            # Parse to appropriate type
            value = self._parse_value(value_str, kw.value_type)

        elif kw.value_type == "int":
            try:
                value = IntPrompt.ask(
                    f"Value for {kw.name}",
                    default=kw.default if isinstance(kw.default, int) else None,
                )
            except Exception:
                return

        elif kw.value_type == "float":
            try:
                value = FloatPrompt.ask(
                    f"Value for {kw.name}",
                    default=kw.default if isinstance(kw.default, (int, float)) else None,
                )
            except Exception:
                return

        elif kw.value_type == "str":
            value = Prompt.ask(
                f"Value for {kw.name}",
                default=str(kw.default) if kw.default else None,
            )

        else:
            value_str = Prompt.ask(
                f"Value for {kw.name}",
                default=str(kw.default) if kw.default is not None else None,
            )
            value = self._parse_value(value_str, kw.value_type)

        if value is not None:
            self.state.set(kw.name, value, kw.section)
            self.console.print(f"[green]Set {kw.name} = {value}[/green]")

    def _parse_value(self, value_str: str, value_type: str) -> Any:
        """Parse a string value to the appropriate type."""
        if not value_str:
            return None

        try:
            if value_type == "int":
                return int(value_str)
            elif value_type == "float":
                return float(value_str)
            else:
                return value_str
        except ValueError:
            return value_str

    def _jump_to_related(self, kw: Keyword) -> None:
        """Show related keywords and let user jump to one."""
        self.console.print("\n[bold]Related keywords:[/bold]")

        related_keywords = []
        for name in kw.related:
            related_kw = self.db.get(name)
            if related_kw:
                related_keywords.append(related_kw)

        if not related_keywords:
            self.console.print("[grey50]No related keywords found[/grey50]")
            return

        table = Table(show_header=False, box=None, padding=(0, 2))
        table.add_column("Key", style="cyan", width=4)
        table.add_column("Keyword")
        table.add_column("Section")
        table.add_column("Current")

        for i, rkw in enumerate(related_keywords):
            current = self.state.get(rkw.name, rkw.section)
            current_str = str(current) if current is not None else "[italic]not set[/italic]"
            table.add_row(str(i + 1), rkw.name, f"&{rkw.section}", current_str)

        table.add_row("B", "[grey50]Back[/grey50]", "", "")
        self.console.print(table)

        choices = [str(i + 1) for i in range(len(related_keywords))] + ["b", "B", "back"]
        choice = Prompt.ask("Jump to", choices=choices, default="b", show_choices=False).lower()

        if choice not in ["b", "back"]:
            try:
                idx = int(choice) - 1
                if 0 <= idx < len(related_keywords):
                    self._edit_keyword(related_keywords[idx])
            except ValueError:
                pass

    def _select_other_section(self) -> None:
        """Show all sections for selection."""
        self.console.print("\n[bold]All namelist sections:[/bold]\n")

        sections = self.db.sections()
        table = Table(show_header=False, box=None, padding=(0, 2))
        table.add_column("Key", style="cyan", width=4)
        table.add_column("Section")
        table.add_column("Keywords")
        table.add_column("Set")

        for i, section in enumerate(sections):
            kw_count = len(self.db.by_section(section))
            set_count = self.state.count_in_section(section)
            set_str = f"[green]{set_count}[/green]" if set_count > 0 else "0"
            table.add_row(str(i + 1), f"&{section}", str(kw_count), set_str)

        table.add_row("B", "[grey50]Back[/grey50]", "", "")
        self.console.print(table)

        choices = [str(i + 1) for i in range(len(sections))] + ["b", "B", "back"]
        choice = Prompt.ask("Select section", choices=choices, default="b", show_choices=False).lower()

        if choice not in ["b", "back"]:
            try:
                idx = int(choice) - 1
                if 0 <= idx < len(sections):
                    self._browse_section(sections[idx])
            except ValueError:
                pass

    def _search_keywords(self) -> None:
        """Search for keywords."""
        self.console.print()
        query = Prompt.ask("Search for")

        if not query:
            return

        results = self.db.search(query, max_results=15)

        if not results:
            self.console.print("[yellow]No keywords found[/yellow]")
            Prompt.ask("Press Enter to continue")
            return

        while True:
            self.console.print(f"\n[bold]Search results for '{query}':[/bold]\n")

            table = Table(show_header=False, box=None, padding=(0, 2))
            table.add_column("Key", style="cyan", width=4)
            table.add_column("Keyword")
            table.add_column("Section", width=10)
            table.add_column("Description")

            for i, kw in enumerate(results):
                table.add_row(str(i + 1), kw.name, f"&{kw.section}", kw.description or "")

            table.add_row("", "", "", "")
            table.add_row("S", "Search again", "", "")
            table.add_row("B", "Back", "", "")
            self.console.print(table)

            choices = [str(i + 1) for i in range(len(results))] + ["s", "S", "b", "B", "back"]
            choice = Prompt.ask("Select", choices=choices, default="b", show_choices=False).lower()

            if choice in ["b", "back"]:
                return
            elif choice == "s":
                # Search again
                self.console.print()
                query = Prompt.ask("Search for")
                if not query:
                    return
                results = self.db.search(query, max_results=15)
                if not results:
                    self.console.print("[yellow]No keywords found[/yellow]")
                    Prompt.ask("Press Enter to continue")
                    return
                # Loop continues with new results
            else:
                try:
                    idx = int(choice) - 1
                    if 0 <= idx < len(results):
                        self._edit_keyword(results[idx])
                except ValueError:
                    pass

    def _show_validation(self) -> None:
        """Show validation results."""
        result = self.validate()

        self.console.print()
        self.console.print("[bold cyan]Validation Results[/bold cyan]")
        self.console.print()

        if result.is_valid and not result.warnings and not result.infos:
            self.console.print("[green]✓ Configuration looks good![/green]")
        else:
            # Group by severity
            for issue in result.errors:
                self.console.print(f"[red]✗ ERROR[/red] [{issue.code}] {issue.message}")
                if issue.suggestion:
                    self.console.print(f"  [italic]→ {issue.suggestion}[/italic]")

            for issue in result.warnings:
                self.console.print(f"[yellow]⚠ WARNING[/yellow] [{issue.code}] {issue.message}")
                if issue.suggestion:
                    self.console.print(f"  [italic]→ {issue.suggestion}[/italic]")

            for issue in result.infos:
                self.console.print(f"[blue]ℹ INFO[/blue] [{issue.code}] {issue.message}")

        self.console.print()
        self.console.print(
            f"[grey50]{len(result.errors)} error(s), {len(result.warnings)} warning(s), "
            f"{len(result.infos)} info(s)[/grey50]"
        )

        Prompt.ask("\nPress Enter to continue")

    def _show_preview(self, comments: bool = True) -> None:
        """Show MDIN preview."""
        self.console.print()
        text = self.preview(comments=comments)

        # Use Syntax highlighting
        syntax = Syntax(text, "fortran", theme="monokai", line_numbers=True)
        self.console.print(Panel(syntax, title="MDIN Preview", border_style="cyan"))

        Prompt.ask("\nPress Enter to continue")

    def _write_file(self) -> None:
        """Write MDIN to file."""
        # Validate first
        result = self.validate()
        if result.errors:
            self.console.print(f"\n[red]⚠ {len(result.errors)} validation error(s)[/red]")
            if not Confirm.ask("Write anyway?", default=False):
                return

        # Show preview
        self.console.print()
        text = self.preview(comments=True)
        syntax = Syntax(text, "fortran", theme="monokai")
        self.console.print(Panel(syntax, title="Preview", border_style="cyan"))

        # Get filename
        filename = Prompt.ask("\nOutput filename", default="mdin")
        if not filename.endswith(".mdin") and "." not in filename:
            filename += ".mdin"

        # Options
        comments = Confirm.ask("Include comments?", default=True)

        # Write
        self.write(filename, comments=comments)

    def _edit_title(self) -> None:
        """Edit the MDIN title."""
        self.console.print(f"\n[bold]Current title:[/bold] {self.state.title}")
        new_title = Prompt.ask("New title", default=self.state.title)
        self.state.title = new_title
        self.console.print(f"[green]Title updated[/green]")

    def _is_category_relevant(self, category: str) -> bool:
        """Check if a category is relevant based on current state."""
        if category in CATEGORY_RELEVANCE:
            try:
                return CATEGORY_RELEVANCE[category](self.state)
            except Exception:
                return True
        return True


# =============================================================================
# Convenience Function
# =============================================================================


def run_mdin_builder() -> None:
    """
    Launch the interactive MDIN builder.

    Convenience function for command-line invocation.
    """
    builder = MdinBuilder()
    builder.run()
