#!/usr/bin/env python3
"""
Code Generator

Generates Python transformer code from TransformerSpec
"""

import logging
from typing import Dict, List, Optional, Any
from datetime import datetime
from textwrap import indent, dedent

try:
    from .data_models import (
        TransformerSpec,
        CenterTypeEnum,
        MatchingStage,
        IntrinsicFilterStage,
        PositionalStage,
        ArithmeticStage,
        ParameterType
    )
except ImportError:
    # Fallback for direct execution
    from data_models import (
        TransformerSpec,
        CenterTypeEnum,
        MatchingStage,
        IntrinsicFilterStage,
        PositionalStage,
        ArithmeticStage,
        ParameterType
    )

logger = logging.getLogger(__name__)


class CodeGenerator:
    """Generate transformer Python code from specification"""

    def __init__(self, spec: TransformerSpec):
        self.spec = spec

    def generate(self) -> str:
        """Generate complete Python module code"""
        sections = []

        # Header
        sections.append(self._generate_header())

        # Imports
        sections.append(self._generate_imports())

        # Class definition
        sections.append(self._generate_class_definition())

        # Class methods
        sections.append(self._generate_evaluate_method())
        sections.append(self._generate_match_components_method())
        sections.append(self._generate_get_transformation_sequence_method())
        sections.append(self._generate_get_site_requirements_method())

        # Optional methods
        if self.spec.parameters:
            sections.append(self._generate_get_parameter_definitions_method())
            sections.append(self._generate_get_parameter_mappings_method())

        if self.spec.required_residue_count > 1:
            sections.append(self._generate_get_required_residue_count_method())

        return "\n\n".join(sections)

    def _generate_header(self) -> str:
        """Generate file header"""
        return f'''#!/usr/bin/env python3
"""
{self.spec.class_name}

{self.spec.description}

Generated by Transformer Creator v2
Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
{f"Template: {self.spec.template_source}" if self.spec.template_source else "Built from scratch"}
"""'''

    def _generate_imports(self) -> str:
        """Generate import statements"""
        return '''import logging
from typing import Any, Dict, List, Optional, Tuple

from proprep.redoxsite_prep.transformation.redox_transformer_framework import (
    RedoxSiteTransformerBase,
    TransformerEvaluation,
    TransformerEvaluationDetail,
    register_redox_transformer
)
from proprep.structure_prep.comprehensive_redox_detector import CenterType

logger = logging.getLogger(__name__)'''

    def _generate_class_definition(self) -> str:
        """Generate class definition and constants"""
        site_types_str = ", ".join(f'"{st}"' for st in self.spec.supported_site_types)
        ff_path = f'"{self.spec.forcefield_path}"' if self.spec.forcefield_path else "None"

        return f'''@register_redox_transformer
class {self.spec.class_name}(RedoxSiteTransformerBase):
    """{self.spec.description}"""

    TRANSFORMER_NAME = "{self.spec.name}"
    DESCRIPTION = "{self.spec.description}"
    SUPPORTED_SITE_TYPES = [{site_types_str}]
    FORCEFIELD_PATH = {ff_path}'''

    def _generate_evaluate_method(self) -> str:
        """Generate evaluate_redox_site method"""
        return '''    @classmethod
    def evaluate_redox_site(cls, redox_site) -> TransformerEvaluation:
        """Evaluate if redox site matches this transformer"""
        all_details = []
        total_requirements_met = 0
        total_requirements = 0

        # Validate centers
        center_met, center_total, center_details = cls.validate_centers_from_requirements(redox_site)
        all_details.extend(center_details)
        total_requirements_met += center_met
        total_requirements += center_total

        # Validate atoms
        atom_met, atom_total, atom_details = cls.validate_atoms_from_requirements(redox_site)
        all_details.extend(atom_details)
        total_requirements_met += atom_met
        total_requirements += atom_total

        # Validate bonds
        bond_met, bond_total, bond_details = cls.validate_bonds_from_requirements(redox_site)
        all_details.extend(bond_details)
        total_requirements_met += bond_met
        total_requirements += bond_total

        # Calculate confidence
        confidence = total_requirements_met / total_requirements if total_requirements > 0 else 0.0
        is_valid = total_requirements_met >= (total_requirements * 0.8)  # 80% threshold

        return TransformerEvaluation(
            is_valid=is_valid,
            confidence=confidence,
            description=cls.DESCRIPTION,
            requirements_met=total_requirements_met,
            total_requirements=total_requirements,
            details=all_details
        )'''

    def _generate_match_components_method(self) -> str:
        """Generate match_components method"""
        # Generate matching logic for each component
        component_matching_code = []

        for comp_name, rule in self.spec.component_matching.rules.items():
            comp_code = self._generate_component_matching_code(comp_name, rule)
            component_matching_code.append(comp_code)

        matching_logic = indent("\n\n".join(component_matching_code), "        ")

        return f'''    @classmethod
    def match_components(cls, redox_site) -> Tuple[Dict[str, Any], List[str]]:
        """Match components in the redox site"""
        matched_components = {{}}
        missing_components = []

{matching_logic}

        return matched_components, missing_components'''

    def _generate_component_matching_code(self, comp_name: str, rule) -> str:
        """Generate matching code for a single component"""
        stages_code = []

        for i, stage in enumerate(rule.stages):
            stage_code = self._generate_stage_code(stage, i, comp_name)
            stages_code.append(stage_code)

        stages_combined = "\n".join(stages_code)

        # Generate the component matching wrapper
        return f'''# Match {comp_name}
# {rule.description}
candidates = list(redox_site.atoms)  # Start with all atoms

{stages_combined}

if len(candidates) == 1:
    matched_components["{comp_name}_id"] = candidates[0].resid
    matched_components["{comp_name}_chain"] = candidates[0].chain
elif len(candidates) == 0:
    missing_components.extend(["{comp_name}_id", "{comp_name}_chain"])
else:
    logger.warning(f"Multiple candidates for {comp_name}: {{len(candidates)}}")
    missing_components.extend(["{comp_name}_id", "{comp_name}_chain"])'''

    def _generate_stage_code(self, stage: MatchingStage, stage_num: int, comp_name: str) -> str:
        """Generate code for a single matching stage"""
        stage_dict = stage.model_dump()
        stage_type = stage_dict.get('type')

        if stage_type == 'intrinsic_filter':
            return self._generate_intrinsic_filter_code(stage_dict)
        elif stage_type == 'positional':
            return self._generate_positional_code(stage_dict)
        elif stage_type == 'arithmetic':
            return self._generate_arithmetic_code(stage_dict)
        elif stage_type == 'exclude_matched':
            return self._generate_exclude_matched_code()
        elif stage_type == 'custom':
            return f"# Custom stage\n{stage_dict.get('code', '# TODO: implement')}"
        else:
            return f"# TODO: Implement {stage_type} stage"

    def _generate_intrinsic_filter_code(self, stage_data: Dict) -> str:
        """Generate code for intrinsic filter stage"""
        code_lines = []
        filters = []

        # Residue name filter
        if 'resname' in stage_data and stage_data['resname']:
            filters.append(f"atom.resname == '{stage_data['resname']}'")
        elif 'resnames' in stage_data and stage_data['resnames']:
            resnames = ", ".join(f"'{rn}'" for rn in stage_data['resnames'])
            filters.append(f"atom.resname in [{resnames}]")

        # Coordinating atom filter - check if atom participates in coordinate bond
        if 'coord_atom' in stage_data and stage_data['coord_atom']:
            coord_atom = stage_data['coord_atom']
            code_lines.append(f"# Find atoms that coordinate through {coord_atom}")
            code_lines.append("coordinating_atoms = set()")
            code_lines.append("for bond in redox_site.bonds:")
            code_lines.append("    if bond.chemical_type == 'coordinate':")
            code_lines.append("        atom1_info = redox_site.coord_to_pdb.get(bond.atom1_coords, {})")
            code_lines.append("        atom2_info = redox_site.coord_to_pdb.get(bond.atom2_coords, {})")
            code_lines.append(f"        if atom1_info.get('atom_name') == '{coord_atom}':")
            code_lines.append("            coordinating_atoms.add((atom1_info['chain'], atom1_info['resid']))")
            code_lines.append(f"        if atom2_info.get('atom_name') == '{coord_atom}':")
            code_lines.append("            coordinating_atoms.add((atom2_info['chain'], atom2_info['resid']))")
            filters.append("(atom.chain, atom.resid) in coordinating_atoms")
        elif 'coord_atoms' in stage_data and stage_data['coord_atoms']:
            coord_atoms = stage_data['coord_atoms']
            atoms_str = ", ".join(f"'{a}'" for a in coord_atoms)
            code_lines.append(f"# Find atoms that coordinate through {atoms_str}")
            code_lines.append("coordinating_atoms = set()")
            code_lines.append("for bond in redox_site.bonds:")
            code_lines.append("    if bond.chemical_type == 'coordinate':")
            code_lines.append("        atom1_info = redox_site.coord_to_pdb.get(bond.atom1_coords, {})")
            code_lines.append("        atom2_info = redox_site.coord_to_pdb.get(bond.atom2_coords, {})")
            code_lines.append(f"        if atom1_info.get('atom_name') in [{atoms_str}]:")
            code_lines.append("            coordinating_atoms.add((atom1_info['chain'], atom1_info['resid']))")
            code_lines.append(f"        if atom2_info.get('atom_name') in [{atoms_str}]:")
            code_lines.append("            coordinating_atoms.add((atom2_info['chain'], atom2_info['resid']))")
            filters.append("(atom.chain, atom.resid) in coordinating_atoms")

        # Distance filter
        has_distance = 'min_distance' in stage_data or 'max_distance' in stage_data
        if has_distance:
            min_dist = stage_data.get('min_distance', 0.0)
            max_dist = stage_data.get('max_distance', 999.0)
            code_lines.append(f"# Filter by distance ({min_dist}-{max_dist} Å from center)")
            code_lines.append("# Get center coordinates")
            code_lines.append("center_coords = None")
            code_lines.append("for center in redox_site.centers:")
            code_lines.append("    center_coords = center.coords")
            code_lines.append("    break")
            code_lines.append("if center_coords:")
            code_lines.append("    def calc_distance(atom):")
            code_lines.append("        dx = atom.coords[0] - center_coords[0]")
            code_lines.append("        dy = atom.coords[1] - center_coords[1]")
            code_lines.append("        dz = atom.coords[2] - center_coords[2]")
            code_lines.append("        return (dx*dx + dy*dy + dz*dz) ** 0.5")
            filters.append(f"({min_dist} <= calc_distance(atom) <= {max_dist})")

        if filters:
            filter_expr = " and ".join(filters)
            code_lines.append(f"# Filter by properties")
            code_lines.append(f"candidates = [atom for atom in candidates if {filter_expr}]")
            return "\n".join(code_lines)
        else:
            return "# No filters in this stage"

    def _generate_positional_code(self, stage_data: Dict) -> str:
        """Generate code for positional stage"""
        sort_by = stage_data.get('sort_by', 'resid')
        position = stage_data.get('position', 0)
        reverse = stage_data.get('reverse', False)
        code_lines = []

        code_lines.append(f"# Sort and select position {position}")

        if sort_by == 'resid':
            sort_code = f"candidates = sorted(candidates, key=lambda a: a.resid, reverse={reverse})"
            code_lines.append(sort_code)
        elif sort_by == 'chain':
            sort_code = f"candidates = sorted(candidates, key=lambda a: a.chain, reverse={reverse})"
            code_lines.append(sort_code)
        elif sort_by == 'distance':
            # Sort by distance from reference component (or center)
            ref_comp = stage_data.get('reference_component', 'center')
            code_lines.append(f"# Sort by distance from {ref_comp}")
            if ref_comp == 'center':
                code_lines.append("# Get center coordinates")
                code_lines.append("ref_coords = None")
                code_lines.append("for center in redox_site.centers:")
                code_lines.append("    ref_coords = center.coords")
                code_lines.append("    break")
            else:
                code_lines.append(f"# Get {ref_comp} coordinates")
                code_lines.append(f"ref_coords = None")
                code_lines.append(f"if '{ref_comp}_chain' in matched_components and '{ref_comp}_id' in matched_components:")
                code_lines.append(f"    ref_chain = matched_components['{ref_comp}_chain']")
                code_lines.append(f"    ref_resid = matched_components['{ref_comp}_id']")
                code_lines.append("    for atom in redox_site.atoms:")
                code_lines.append("        if atom.chain == ref_chain and atom.resid == ref_resid:")
                code_lines.append("            ref_coords = atom.coords")
                code_lines.append("            break")
            code_lines.append("if ref_coords:")
            code_lines.append("    def calc_dist(atom):")
            code_lines.append("        dx = atom.coords[0] - ref_coords[0]")
            code_lines.append("        dy = atom.coords[1] - ref_coords[1]")
            code_lines.append("        dz = atom.coords[2] - ref_coords[2]")
            code_lines.append("        return (dx*dx + dy*dy + dz*dz) ** 0.5")
            code_lines.append(f"    candidates = sorted(candidates, key=calc_dist, reverse={reverse})")
        else:
            code_lines.append(f"# TODO: Sort by {sort_by}")

        select_code = f"candidates = [candidates[{position}]] if len(candidates) > {abs(position)} else candidates"
        code_lines.append(select_code)

        return "\n".join(code_lines)

    def _generate_arithmetic_code(self, stage_data: Dict) -> str:
        """Generate code for arithmetic stage"""
        base_comp = stage_data.get('base_component')
        operation = stage_data.get('operation', 'add')
        value = stage_data.get('value', 0)

        op_symbol = '+' if operation == 'add' else '-'

        return f'''# Calculate from {base_comp}
if "{base_comp}_id" in matched_components:
    target_resid = matched_components["{base_comp}_id"] {op_symbol} {value}
    target_chain = matched_components["{base_comp}_chain"]
    candidates = [atom for atom in candidates if atom.resid == target_resid and atom.chain == target_chain]'''

    def _generate_exclude_matched_code(self) -> str:
        """Generate code for exclude matched stage"""
        return '''# Exclude already matched
matched_residues = {(matched_components.get(f"{k}_chain"), matched_components.get(f"{k}_id"))
                    for k in matched_components.keys() if k.endswith("_id")}
candidates = [atom for atom in candidates if (atom.chain, atom.resid) not in matched_residues]'''

    def _generate_get_transformation_sequence_method(self) -> str:
        """Generate get_transformation_sequence method"""
        transformations_list = []

        for trans in self.spec.transformation_sequence.transformations:
            trans_dict = self._format_transformation(trans)
            transformations_list.append(trans_dict)

        transformations_str = indent(",\n".join(transformations_list), "            ")

        return f'''    @classmethod
    def get_transformation_sequence(cls, components: Dict[str, Any], parameters: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Generate transformation sequence"""
        transformations = [
{transformations_str}
        ]
        return transformations'''

    def _format_transformation(self, trans) -> str:
        """Format a single transformation as Python dict"""
        selector = trans.selector.model_dump(exclude_none=True)
        action = trans.action.model_dump(exclude_none=True)

        # Format selector
        selector_lines = [f'"{k}": {self._format_value(v)}' for k, v in selector.items()]
        selector_str = "{" + ", ".join(selector_lines) + "}"

        # Format action
        action_lines = [f'"{k}": {self._format_value(v)}' for k, v in action.items()]
        action_str = "{" + ", ".join(action_lines) + "}"

        return f'''{{
                "id": "{trans.id}",
                "description": "{trans.description}",
                "selector": {selector_str},
                "action": {action_str}
            }}'''

    def _format_value(self, value: Any) -> str:
        """Format a value for Python code"""
        if isinstance(value, str):
            # Check if it's a component reference (starts with lowercase letter)
            if value and value[0].islower() and '_' in value:
                return f'components["{value}"]'
            else:
                return f'"{value}"'
        elif isinstance(value, dict):
            items = [f'"{k}": "{v}"' for k, v in value.items()]
            return "{" + ", ".join(items) + "}"
        elif isinstance(value, list):
            items = [f'"{item}"' for item in value]
            return "[" + ", ".join(items) + "]"
        elif isinstance(value, bool):
            return str(value)
        elif isinstance(value, (int, float)):
            return str(value)
        else:
            return f'"{value}"'

    def _generate_get_site_requirements_method(self) -> str:
        """Generate get_site_requirements method"""
        reqs = self.spec.site_requirements

        # Format centers
        center_types_str = ", ".join(f"CenterType.{ct.name}" for ct in reqs.centers.center_types)
        elements_str = str(reqs.centers.elements) if reqs.centers.elements else "None"

        centers_dict = f'''{{
            "required_count": {reqs.centers.required_count},
            "center_types": [{center_types_str}],
            "elements": {elements_str}
        }}'''

        # Format atoms
        atoms_dict = "None"
        if reqs.atoms:
            residues_items = []
            for resname, req in reqs.atoms.required_residues.items():
                max_str = str(req.max_count) if req.max_count else "None"
                residues_items.append(f'"{resname}": {{"min_count": {req.min_count}, "max_count": {max_str}}}')

            residues_str = "{" + ", ".join(residues_items) + "}"
            alt_groups_str = str(reqs.atoms.alternative_groups) if reqs.atoms.alternative_groups else "None"

            atoms_dict = f'''{{
            "required_residues": {residues_str},
            "alternative_groups": {alt_groups_str}
        }}'''

        # Format bonds (simplified)
        bonds_dict = "None"
        if reqs.bonds:
            bonds_dict = '{"required_bond_groups": [], "require_one_group": False}  # TODO: Implement'

        return f'''    @classmethod
    def get_site_requirements(cls) -> Dict[str, Any]:
        """Return site matching requirements"""
        return {{
            "centers": {indent(centers_dict, "            ").strip()},
            "atoms": {indent(atoms_dict, "            ").strip()},
            "bonds": {bonds_dict}
        }}'''

    def _generate_get_parameter_definitions_method(self) -> str:
        """Generate get_parameter_definitions method"""
        if not self.spec.parameters:
            return ""

        params_items = []
        for name, defn in self.spec.parameters.definitions.items():
            param_dict_items = [
                f'"description": "{defn.description}"',
                f'"type": "{defn.type.value}"'
            ]

            if defn.options:
                options_str = ", ".join(f'"{opt}"' for opt in defn.options)
                param_dict_items.append(f'"options": [{options_str}]')

            if defn.default:
                param_dict_items.append(f'"default": "{defn.default}"')

            if defn.value:
                param_dict_items.append(f'"value": "{defn.value}"')

            if defn.note:
                param_dict_items.append(f'"note": "{defn.note}"')

            param_dict = "{" + ", ".join(param_dict_items) + "}"
            params_items.append(f'"{name}": {param_dict}')

        params_str = indent(",\n".join(params_items), "            ")

        return f'''    @classmethod
    def get_parameter_definitions(cls) -> Dict[str, Any]:
        """Return parameter definitions"""
        return {{
{params_str}
        }}'''

    def _generate_get_parameter_mappings_method(self) -> str:
        """Generate get_parameter_mappings method"""
        if not self.spec.parameters or not self.spec.parameters.mappings:
            return ""

        mappings_items = []
        for combo, mapping in self.spec.parameters.mappings.items():
            mapping_items = [f'"{k}": "{v}"' for k, v in mapping.items()]
            mapping_dict = "{" + ", ".join(mapping_items) + "}"
            mappings_items.append(f'"{combo}": {mapping_dict}')

        mappings_str = indent(",\n".join(mappings_items), "            ")

        return f'''    @classmethod
    def get_parameter_mappings(cls, parameters: Dict[str, Any]) -> Dict[str, str]:
        """Map parameters to residue names"""
        # Generate parameter combination key
        param_key = "_".join([parameters.get(p, "") for p in cls.get_parameter_definitions().keys()])

        mappings = {{
{mappings_str}
        }}

        return mappings.get(param_key, {{}})'''

    def _generate_get_required_residue_count_method(self) -> str:
        """Generate get_required_residue_count method"""
        return f'''    @classmethod
    def get_required_residue_count(cls) -> int:
        """Number of residue IDs needed for this transformer"""
        return {self.spec.required_residue_count}'''
