"""
Code generator for Transformer Creator v3.

Takes a TransformerSpecV3 and generates a Python transformer class
that inherits from RedoxSiteTransformerBase.
"""

import logging
from datetime import datetime
from textwrap import dedent, indent
from typing import Any, Dict, List, Optional, Tuple

from .data_models import (
    CommandType,
    EditCommand,
    EditingPass,
    ParameterSpec,
    RoleDefinition,
    TransformerSpecV3,
    ConnectivityPhrase,
    SpatialPhrase,
    SequencePhrase,
)

logger = logging.getLogger(__name__)


class CodeGeneratorV3:
    """Generate transformer Python code from a v3 specification."""

    def __init__(
        self,
        spec: TransformerSpecV3,
        roles: Dict[str, RoleDefinition],
        resolved: Dict[str, Tuple[str, int]],
    ):
        self.spec = spec
        self.roles = roles
        self.resolved = resolved
        self._class_name = self._to_class_name(spec.name)

    def generate(self) -> str:
        """Generate complete Python module code."""
        sections = [
            self._gen_header(),
            self._gen_imports(),
            self._gen_class_def(),
            self._gen_evaluate_method(),
            self._gen_site_requirements_method(),
            self._gen_match_components_method(),
            self._gen_transformation_sequence_method(),
            self._gen_residue_count_method(),
            self._gen_residue_space_plan_method(),
            self._gen_parameter_definitions_method(),
            self._gen_validate_parameters_method(),
            self._gen_parameter_mappings_method(),
        ]
        return "\n\n".join(s for s in sections if s) + "\n"

    # ===== HEADER + IMPORTS =====

    def _gen_header(self) -> str:
        return f'''#!/usr/bin/env python3
"""
{self._class_name}

{self.spec.description}

Generated by Transformer Creator v3
Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""'''

    def _gen_imports(self) -> str:
        return '''import logging
import math
from typing import Any, Dict, List, Optional, Tuple

from proprep.redoxsite_prep.transformation.redox_transformer_framework import (
    RedoxSiteTransformerBase,
    TransformerEvaluation,
    TransformerEvaluationDetail,
    register_redox_transformer
)
from proprep.structure_prep.comprehensive_redox_detector import CenterType

logger = logging.getLogger(__name__)'''

    # ===== CLASS DEFINITION =====

    def _gen_class_def(self) -> str:
        site_types = ", ".join(f'"{self.spec.name}"')
        ff = f'"{self.spec.forcefield_path}"' if self.spec.forcefield_path else "None"
        return f'''@register_redox_transformer
class {self._class_name}(RedoxSiteTransformerBase):
    """{self.spec.description}"""

    TRANSFORMER_NAME = "{self.spec.name}"
    DESCRIPTION = "{self.spec.description}"
    SUPPORTED_SITE_TYPES = [{site_types}]
    FORCEFIELD_PATH = {ff}'''

    # ===== EVALUATE =====

    def _gen_evaluate_method(self) -> str:
        return '''    @classmethod
    def evaluate_redox_site(cls, redox_site) -> TransformerEvaluation:
        """Evaluate if redox site matches this transformer."""
        all_details = []
        total_met = 0
        total_req = 0

        center_met, center_total, center_details = cls.validate_centers_from_requirements(redox_site)
        all_details.extend(center_details)
        total_met += center_met
        total_req += center_total

        atom_met, atom_total, atom_details = cls.validate_atoms_from_requirements(redox_site)
        all_details.extend(atom_details)
        total_met += atom_met
        total_req += atom_total

        bond_met, bond_total, bond_details = cls.validate_bonds_from_requirements(redox_site)
        all_details.extend(bond_details)
        total_met += bond_met
        total_req += bond_total

        confidence = total_met / total_req if total_req > 0 else 0.0
        is_valid = total_met >= (total_req * 0.8)

        return TransformerEvaluation(
            is_valid=is_valid,
            confidence=confidence,
            description=cls.DESCRIPTION,
            requirements_met=total_met,
            total_requirements=total_req,
            details=all_details
        )'''

    # ===== SITE REQUIREMENTS =====

    def _gen_site_requirements_method(self) -> str:
        # Build from roles
        center_roles = [r for r in self.roles.values() if r.is_center]
        center_count = len(center_roles) or 1

        # Determine center types from site
        center_types = set()
        for center in self.spec.roles:
            if center.is_center:
                # Map to CenterType based on what we know
                for c in getattr(self, '_site_centers', []):
                    if hasattr(c, 'center_type'):
                        center_types.add(c.center_type)

        # Build residue requirements
        resname_counts: Dict[str, int] = {}
        for role in self.roles.values():
            if role.is_center:
                continue
            rn = role.resname
            resname_counts[rn] = resname_counts.get(rn, 0) + 1

        residue_lines = []
        for resname, count in sorted(resname_counts.items()):
            residue_lines.append(
                f'"{resname}": {{"min_count": {count}, "max_count": {count}}}'
            )

        # Include center resnames
        center_resnames = set()
        for r in self.roles.values():
            if r.is_center:
                center_resnames.add(r.resname)
                center_resnames.update(r.alt_resnames)

        for rn in sorted(center_resnames):
            residue_lines.append(
                f'"{rn}": {{"min_count": 0, "max_count": 1}}'
            )

        residues_str = ",\n                    ".join(residue_lines)

        # Alt groups
        alt_groups = []
        for r in self.roles.values():
            if r.alt_resnames:
                group = [r.resname] + r.alt_resnames
                alt_groups.append(group)
        alt_str = str(alt_groups) if alt_groups else "None"

        return f'''    @classmethod
    def get_site_requirements(cls) -> Dict[str, Any]:
        """Return site matching requirements."""
        return {{
            "centers": {{
                "required_count": {center_count},
                "center_types": [CenterType.ORGANOMETALLIC_COFACTOR],
                "residue_names": {sorted(center_resnames) if center_resnames else "None"}
            }},
            "atoms": {{
                "required_residues": {{
                    {residues_str}
                }},
                "alternative_groups": {alt_str}
            }},
            "bonds": None
        }}'''

    # ===== MATCH COMPONENTS =====

    def _gen_match_components_method(self) -> str:
        """Generate match_components from relationship phrases."""
        matching_code_lines = []

        for label, role in self.roles.items():
            if role.is_center:
                matching_code_lines.extend(self._gen_center_matching(label, role))
            else:
                matching_code_lines.extend(self._gen_role_matching(label, role))

        matching_code = "\n".join(matching_code_lines)

        return f'''    @classmethod
    def match_components(cls, redox_site) -> Tuple[Dict[str, Any], List[str]]:
        """Match components using relationship constraints."""
        matched = {{}}
        missing = []

{indent(matching_code, "        ")}

        return matched, missing'''

    def _gen_center_matching(self, label: str, role: RoleDefinition) -> List[str]:
        """Generate code to match a center role."""
        resnames = [role.resname] + role.alt_resnames
        resnames_str = ", ".join(f'"{r}"' for r in resnames)
        return [
            f"# Match {label} (center)",
            f"center_candidates = [c for c in redox_site.centers",
            f"                     if hasattr(c, 'resname') and c.resname in [{resnames_str}]]",
            f"if center_candidates:",
            f"    matched['{label}_id'] = center_candidates[0].resid",
            f"    matched['{label}_chain'] = center_candidates[0].chain",
            f"else:",
            f"    missing.extend(['{label}_id', '{label}_chain'])",
            "",
        ]

    def _gen_role_matching(self, label: str, role: RoleDefinition) -> List[str]:
        """Generate code to match a non-center role from its phrases."""
        lines = [f"# Match {label}"]
        lines.append(f"candidates_{label} = [a for a in redox_site.atoms if a.resname == '{role.resname}']")
        lines.append(f"# Deduplicate to unique residues")
        lines.append(f"seen_{label} = set()")
        lines.append(f"unique_{label} = []")
        lines.append(f"for a in candidates_{label}:")
        lines.append(f"    rkey = (a.chain, a.resid)")
        lines.append(f"    if rkey not in seen_{label}:")
        lines.append(f"        seen_{label}.add(rkey)")
        lines.append(f"        unique_{label}.append(a)")
        lines.append(f"candidates_{label} = unique_{label}")

        # Generate constraint code for each phrase
        for phrase in role.phrases:
            lines.extend(self._gen_phrase_code(label, phrase))

        # Exclude already matched
        lines.append(f"# Exclude already matched residues")
        lines.append(f"matched_keys = {{(matched.get(f'{{k}}_chain'), matched.get(f'{{k}}_id'))")
        lines.append(f"                for k in set(k.rsplit('_', 1)[0] for k in matched if k.endswith('_id'))}}")
        lines.append(f"candidates_{label} = [a for a in candidates_{label}")
        lines.append(f"                      if (a.chain, a.resid) not in matched_keys]")

        # Assign result
        lines.append(f"if len(candidates_{label}) == 1:")
        lines.append(f"    matched['{label}_id'] = candidates_{label}[0].resid")
        lines.append(f"    matched['{label}_chain'] = candidates_{label}[0].chain")
        lines.append(f"elif len(candidates_{label}) == 0:")
        lines.append(f"    missing.extend(['{label}_id', '{label}_chain'])")
        lines.append(f"else:")
        lines.append(f"    logger.warning(f'Multiple candidates for {label}: {{len(candidates_{label})}}')")
        lines.append(f"    # Take first candidate as fallback")
        lines.append(f"    matched['{label}_id'] = candidates_{label}[0].resid")
        lines.append(f"    matched['{label}_chain'] = candidates_{label}[0].chain")
        lines.append("")

        return lines

    def _gen_phrase_code(self, label: str, phrase) -> List[str]:
        """Generate constraint code for a single phrase."""
        if isinstance(phrase, ConnectivityPhrase):
            return self._gen_connectivity_code(label, phrase)
        elif isinstance(phrase, SpatialPhrase):
            return self._gen_spatial_code(label, phrase)
        elif isinstance(phrase, SequencePhrase):
            return self._gen_sequence_code(label, phrase)
        return []

    def _gen_connectivity_code(self, label: str, phrase: ConnectivityPhrase) -> List[str]:
        """Generate code for a connectivity constraint."""
        lines = [f"# Connectivity: {phrase.raw_text}"]
        lines.append(f"bonded_{label} = set()")
        lines.append(f"for bond in redox_site.bonds:")

        # Build bond matching conditions
        conditions = []
        if phrase.bond_type:
            conditions.append(f"bond.chemical_type == '{phrase.bond_type}'")

        lines.append(f"    info1 = redox_site.coord_to_pdb.get(bond.atom1_coords, {{}})")
        lines.append(f"    info2 = redox_site.coord_to_pdb.get(bond.atom2_coords, {{}})")
        lines.append(f"    if not info1 or not info2:")
        lines.append(f"        continue")

        if conditions:
            cond_str = " and ".join(conditions)
            lines.append(f"    if not ({cond_str}):")
            lines.append(f"        continue")

        # Check both orientations
        target_role = phrase.target_role
        src_atom = phrase.source_atom
        tgt_atom = phrase.target_atom

        # Build the check for source atom matching candidate and target atom matching target role
        lines.append(f"    # Check both bond orientations")
        lines.append(f"    for src_info, tgt_info in [(info1, info2), (info2, info1)]:")

        tgt_checks = []
        if tgt_atom:
            tgt_checks.append(f"tgt_info.get('atom_name') == '{tgt_atom}'")
        # Target must be in the target role's residue
        lines.append(f"        tgt_key = (tgt_info.get('chain', ''), tgt_info.get('resid', 0))")
        lines.append(f"        if '{target_role}_id' in matched:")
        lines.append(f"            if tgt_key != (matched['{target_role}_chain'], matched['{target_role}_id']):")
        lines.append(f"                continue")

        if tgt_checks:
            lines.append(f"            if not ({' and '.join(tgt_checks)}):")
            lines.append(f"                continue")

        src_checks = []
        if src_atom:
            src_checks.append(f"src_info.get('atom_name') == '{src_atom}'")

        if src_checks:
            lines.append(f"            if {' and '.join(src_checks)}:")
            lines.append(f"                bonded_{label}.add((src_info.get('chain', ''), src_info.get('resid', 0)))")
        else:
            lines.append(f"            bonded_{label}.add((src_info.get('chain', ''), src_info.get('resid', 0)))")

        lines.append(f"if bonded_{label}:")
        lines.append(f"    candidates_{label} = [a for a in candidates_{label}")
        lines.append(f"                          if (a.chain, a.resid) in bonded_{label}]")

        return lines

    def _gen_spatial_code(self, label: str, phrase: SpatialPhrase) -> List[str]:
        """Generate code for a spatial constraint."""
        lines = [f"# Spatial: {phrase.raw_text}"]
        target_role = phrase.target_role

        # Get reference coordinates
        if phrase.target_atom:
            lines.append(f"ref_coords_{label} = None")
            lines.append(f"for a in redox_site.atoms:")
            lines.append(f"    if a.chain == matched.get('{target_role}_chain') and "
                        f"a.resid == matched.get('{target_role}_id') and "
                        f"a.atom_name == '{phrase.target_atom}':")
            lines.append(f"        ref_coords_{label} = a.coords")
            lines.append(f"        break")
        else:
            lines.append(f"# Use closest atom on target")
            lines.append(f"ref_atoms_{label} = [a for a in redox_site.atoms")
            lines.append(f"                     if a.chain == matched.get('{target_role}_chain') and "
                        f"a.resid == matched.get('{target_role}_id')]")

        # Distance calculation
        lines.append(f"def _dist_{label}(candidate):")
        if phrase.source_atom:
            lines.append(f"    # Use specific atom on candidate")
            lines.append(f"    src = None")
            lines.append(f"    for a in redox_site.atoms:")
            lines.append(f"        if a.chain == candidate.chain and a.resid == candidate.resid and a.atom_name == '{phrase.source_atom}':")
            lines.append(f"            src = a.coords")
            lines.append(f"            break")
            lines.append(f"    if src is None:")
            lines.append(f"        return float('inf')")
        else:
            lines.append(f"    src = candidate.coords")

        if phrase.target_atom:
            lines.append(f"    if ref_coords_{label} is None:")
            lines.append(f"        return float('inf')")
            lines.append(f"    dx = src[0] - ref_coords_{label}[0]")
            lines.append(f"    dy = src[1] - ref_coords_{label}[1]")
            lines.append(f"    dz = src[2] - ref_coords_{label}[2]")
            lines.append(f"    return math.sqrt(dx*dx + dy*dy + dz*dz)")
        else:
            lines.append(f"    min_d = float('inf')")
            lines.append(f"    for ref in ref_atoms_{label}:")
            lines.append(f"        dx = src[0] - ref.coords[0]")
            lines.append(f"        dy = src[1] - ref.coords[1]")
            lines.append(f"        dz = src[2] - ref.coords[2]")
            lines.append(f"        d = math.sqrt(dx*dx + dy*dy + dz*dz)")
            lines.append(f"        if d < min_d:")
            lines.append(f"            min_d = d")
            lines.append(f"    return min_d")

        if phrase.comparison == "closest":
            lines.append(f"if candidates_{label}:")
            lines.append(f"    candidates_{label} = [min(candidates_{label}, key=_dist_{label})]")
        elif phrase.comparison == "farthest":
            lines.append(f"if candidates_{label}:")
            lines.append(f"    candidates_{label} = [max(candidates_{label}, key=_dist_{label})]")
        elif phrase.comparison == "within":
            lines.append(f"candidates_{label} = [c for c in candidates_{label} if _dist_{label}(c) <= {phrase.distance}]")

        return lines

    def _gen_sequence_code(self, label: str, phrase: SequencePhrase) -> List[str]:
        """Generate code for a sequence constraint."""
        lines = [f"# Sequence: {phrase.raw_text}"]

        if phrase.offset is not None and phrase.offset_target_role:
            target = phrase.offset_target_role
            lines.append(f"if '{target}_id' in matched:")
            lines.append(f"    target_resid = matched['{target}_id'] + {phrase.offset}")
            lines.append(f"    target_chain = matched['{target}_chain']")
            lines.append(f"    candidates_{label} = [a for a in candidates_{label}")
            lines.append(f"                          if a.resid == target_resid and a.chain == target_chain]")

        elif phrase.resid_comparison and phrase.comparison_target_role:
            target = phrase.comparison_target_role
            op = "<" if phrase.resid_comparison == "lower" else ">"
            lines.append(f"if '{target}_id' in matched:")
            lines.append(f"    candidates_{label} = [a for a in candidates_{label}")
            lines.append(f"                          if a.resid {op} matched['{target}_id']]")

        elif phrase.chain_relation and phrase.chain_target_role:
            target = phrase.chain_target_role
            if phrase.chain_relation == "same":
                lines.append(f"if '{target}_chain' in matched:")
                lines.append(f"    candidates_{label} = [a for a in candidates_{label}")
                lines.append(f"                          if a.chain == matched['{target}_chain']]")
            else:
                lines.append(f"if '{target}_chain' in matched:")
                lines.append(f"    candidates_{label} = [a for a in candidates_{label}")
                lines.append(f"                          if a.chain != matched['{target}_chain']]")

        return lines

    # ===== TRANSFORMATION SEQUENCE =====

    def _gen_transformation_sequence_method(self) -> str:
        """Generate get_transformation_sequence from editing passes."""
        transform_lines = []

        for editing_pass in self.spec.editing_passes:
            transform_lines.append(f"# {editing_pass.description}")
            for cmd in editing_pass.commands:
                transform_lines.extend(self._gen_command_code(cmd))

        transforms_code = "\n".join(transform_lines)

        has_params = self.spec.parameters and any(
            p.param_type == "choice" for p in self.spec.parameters.parameters
        )

        mappings_line = ""
        if has_params:
            mappings_line = "        mappings = cls.get_parameter_mappings(parameters)\n"

        return f'''    @classmethod
    def get_transformation_sequence(cls, components: Dict[str, Any], parameters: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Generate transformation sequence."""
{mappings_line}        transformations = []

{indent(transforms_code, "        ")}

        return transformations'''

    def _gen_command_code(self, cmd: EditCommand) -> List[str]:
        """Generate transformation dict code for a single command."""
        lines = []

        if cmd.command_type == CommandType.RENAME_RESIDUE:
            role = cmd.source_role
            new_name = cmd.new_resname

            # Check if this name is parameter-dependent
            if self.spec.parameters and role in self.spec.parameters.state_dependent_roles:
                new_name_expr = f'mappings.get("{role}", "{new_name}")'
            else:
                new_name_expr = f'"{new_name}"'

            lines.append(f'transformations.append({{')
            lines.append(f'    "id": "rename_{role}",')
            lines.append(f'    "description": "Rename {role}",')
            lines.append(f'    "selector": {{')
            lines.append(f'        "chain_id": components["{role}_chain"],')
            lines.append(f'        "residue_id": components["{role}_id"]')
            lines.append(f'    }},')
            lines.append(f'    "action": {{')
            lines.append(f'        "change_residue_name": {new_name_expr}')
            lines.append(f'    }}')
            lines.append(f'}})')

        elif cmd.command_type == CommandType.RENAME_ATOMS:
            role = cmd.source_role
            rename_dict = dict(zip(cmd.old_atom_names, cmd.new_atom_names))
            lines.append(f'transformations.append({{')
            lines.append(f'    "id": "rename_atoms_{role}",')
            lines.append(f'    "description": "Rename atoms on {role}",')
            lines.append(f'    "selector": {{')
            lines.append(f'        "chain_id": components["{role}_chain"],')
            lines.append(f'        "residue_id": components["{role}_id"],')
            lines.append(f'        "atom_names": {list(cmd.old_atom_names)}')
            lines.append(f'    }},')
            lines.append(f'    "action": {{')
            lines.append(f'        "rename_atoms": {rename_dict}')
            lines.append(f'    }}')
            lines.append(f'}})')

        elif cmd.command_type == CommandType.MOVE_ATOMS:
            role = cmd.source_role
            target = cmd.target_role
            lines.append(f'transformations.append({{')
            lines.append(f'    "id": "move_{role}_to_{target}",')
            lines.append(f'    "description": "Move atoms from {role} to {target}",')
            lines.append(f'    "selector": {{')
            lines.append(f'        "chain_id": components["{role}_chain"],')
            lines.append(f'        "residue_id": components["{role}_id"],')
            lines.append(f'        "atom_names": {list(cmd.atom_names)}')
            lines.append(f'    }},')
            lines.append(f'    "action": {{')
            lines.append(f'        "change_residue_id": components["{target}_id"],')
            lines.append(f'        "change_chain_id": components["{target}_chain"]')
            lines.append(f'    }}')
            lines.append(f'}})')

        elif cmd.command_type == CommandType.MOVE_ATOMS_NEW:
            role = cmd.source_role
            new_role = cmd.new_role_label
            lines.append(f'transformations.append({{')
            lines.append(f'    "id": "move_{role}_to_{new_role}",')
            lines.append(f'    "description": "Extract {new_role} from {role}",')
            lines.append(f'    "selector": {{')
            lines.append(f'        "chain_id": components["{role}_chain"],')
            lines.append(f'        "residue_id": components["{role}_id"],')
            lines.append(f'        "atom_names": {list(cmd.atom_names)}')
            lines.append(f'    }},')
            lines.append(f'    "action": {{')
            lines.append(f'        "change_residue_name": "{cmd.new_residue_name}",')
            lines.append(f'        "change_residue_id": components["{new_role}_id"],')
            lines.append(f'        "change_chain_id": components["{role}_chain"]')
            lines.append(f'    }}')
            lines.append(f'}})')

        elif cmd.command_type == CommandType.HETATM:
            role = cmd.source_role
            lines.append(f'transformations.append({{')
            lines.append(f'    "id": "hetatm_{role}",')
            lines.append(f'    "description": "Convert {role} to HETATM",')
            lines.append(f'    "selector": {{')
            lines.append(f'        "chain_id": components["{role}_chain"],')
            lines.append(f'        "residue_id": components["{role}_id"]')
            lines.append(f'    }},')
            lines.append(f'    "action": {{')
            lines.append(f'        "convert_to_hetatm": True')
            lines.append(f'    }}')
            lines.append(f'}})')

        elif cmd.command_type == CommandType.ATOM:
            role = cmd.source_role
            lines.append(f'transformations.append({{')
            lines.append(f'    "id": "atom_{role}",')
            lines.append(f'    "description": "Convert {role} to ATOM",')
            lines.append(f'    "selector": {{')
            lines.append(f'        "chain_id": components["{role}_chain"],')
            lines.append(f'        "residue_id": components["{role}_id"]')
            lines.append(f'    }},')
            lines.append(f'    "action": {{')
            lines.append(f'        "convert_to_hetatm": False')
            lines.append(f'    }}')
            lines.append(f'}})')

        return lines

    # ===== RESIDUE METHODS =====

    def _gen_residue_count_method(self) -> str:
        return f'''    @classmethod
    def get_required_residue_count(cls) -> int:
        """Number of residue IDs needed."""
        return {self.spec.required_residue_count}'''

    def _gen_residue_space_plan_method(self) -> str:
        # Build plan from new roles
        plan_items = ['"center": 0']
        offset = 1
        for editing_pass in self.spec.editing_passes:
            for cmd in editing_pass.commands:
                if cmd.command_type == CommandType.MOVE_ATOMS_NEW:
                    plan_items.append(f'"{cmd.new_role_label}": {offset}')
                    offset += 1

        plan_str = ", ".join(plan_items)
        return f'''    @classmethod
    def get_residue_space_plan(cls, components: Dict[str, Any]) -> Dict[str, int]:
        """Define residue ID allocation."""
        return {{{plan_str}}}'''

    # ===== PARAMETER METHODS =====

    def _gen_parameter_definitions_method(self) -> str:
        if not self.spec.parameters or not self.spec.parameters.parameters:
            return '''    @classmethod
    def get_parameter_definitions(cls) -> Dict[str, Any]:
        """No parameters required."""
        return {}'''

        param_lines = []
        for p in self.spec.parameters.parameters:
            items = [f'"description": "{p.description}"', f'"type": "{p.param_type}"']
            if p.param_type == "choice":
                opts = ", ".join(f'"{o}"' for o in p.options)
                items.append(f'"options": [{opts}]')
                items.append(f'"default": "{p.default}"')
            else:
                items.append(f'"value": "{p.fixed_value}"')
                if p.note:
                    items.append(f'"note": "{p.note}"')
            param_str = ", ".join(items)
            param_lines.append(f'"{p.name}": {{{param_str}}}')

        params_code = ",\n            ".join(param_lines)
        return f'''    @classmethod
    def get_parameter_definitions(cls) -> Dict[str, Any]:
        """Parameter definitions."""
        return {{
            {params_code}
        }}'''

    def _gen_validate_parameters_method(self) -> str:
        if not self.spec.parameters or not self.spec.parameters.parameters:
            return '''    @classmethod
    def validate_parameters(cls, parameters: Dict[str, Any]) -> Tuple[bool, str]:
        """Always valid — no parameters."""
        return True, "No parameters required"'''

        return '''    @classmethod
    def validate_parameters(cls, parameters: Dict[str, Any]) -> Tuple[bool, str]:
        """Validate parameter values."""
        param_defs = cls.get_parameter_definitions()
        for name, defn in param_defs.items():
            if name not in parameters:
                return False, f"Missing parameter: {name}"
            if defn["type"] == "choice" and parameters[name] not in defn["options"]:
                return False, f"Invalid {name}: {parameters[name]}. Options: {defn['options']}"
        return True, "Parameters valid"'''

    def _gen_parameter_mappings_method(self) -> str:
        if not self.spec.parameters or not self.spec.parameters.name_mappings:
            return '''    @classmethod
    def get_parameter_mappings(cls, parameters: Dict[str, Any]) -> Dict[str, str]:
        """No parameter mappings."""
        return {}'''

        # Build mappings dict
        mapping_lines = []
        for combo_key, mapping in self.spec.parameters.name_mappings.items():
            items = ", ".join(f'"{k}": "{v}"' for k, v in mapping.items())
            mapping_lines.append(f'"{combo_key}": {{{items}}}')

        mappings_code = ",\n            ".join(mapping_lines)

        # Build key construction from choice params
        choice_params = [p for p in self.spec.parameters.parameters if p.param_type == "choice"]
        key_parts = [f'parameters.get("{p.name}", "{p.default}")' for p in choice_params]
        key_expr = ' + "_" + '.join(key_parts) if len(key_parts) > 1 else key_parts[0] if key_parts else '""'

        return f'''    @classmethod
    def get_parameter_mappings(cls, parameters: Dict[str, Any]) -> Dict[str, str]:
        """Map parameters to residue names."""
        param_key = {key_expr}
        mappings = {{
            {mappings_code}
        }}
        return mappings.get(param_key, {{}})'''

    # ===== UTILITIES =====

    @staticmethod
    def _to_class_name(snake: str) -> str:
        """Convert snake_case to CamelCase + 'Transformer'."""
        return "".join(w.capitalize() for w in snake.split("_")) + "Transformer"
