# module_registry.py
"""
Shared Module Registry for PDB Processor

This file defines a shared registry that modules can use to register themselves.
"""

import logging
from typing import Any, Dict, List, Optional, Type

from proprep.utils.workspace import Workspace


# Workspace keys that all denote "a structure is loaded" — they
# collapse to a single friendly phrase in unmet-prerequisite notes so
# the menu says "a loaded structure" rather than listing seven keys.
_STRUCTURE_KEYS = {
    "rcsb_pdb_file", "local_pdb_file", "alphafold_pdb_file",
    "alphafill_pdb_file", "alphafold_homolog_pdb_file",
    "aligned_target_pdb_file", "aligned_ref_pdb_file",
    "structure", "pdb_file",
}

# Friendly phrases for specific unmet workspace keys. Anything not
# listed (and not a structure key) falls back to a de-underscored name.
_REQUIREMENT_PHRASES = {
    "detected_redox_sites": "detected redox sites — run Redox Site Detector first",
    "parm7_file": "a topology — run Topology Generator first",
    "rst7_file": "coordinates (rst7)",
}


def _friendly_requirement(unmet_requirements: List[str]) -> str:
    """Turn unmet requirement strings (each possibly pipe-OR, e.g.
    ``"rcsb_pdb_file | local_pdb_file"``) into a short human phrase
    for the menu, e.g. ``"a loaded structure"``."""
    phrases: List[str] = []
    for req in unmet_requirements:
        alternatives = [k.strip() for k in req.split("|") if k.strip()]
        if any(alt in _STRUCTURE_KEYS for alt in alternatives):
            phrase = "a loaded structure"
        else:
            phrase = next(
                (_REQUIREMENT_PHRASES[alt] for alt in alternatives
                 if alt in _REQUIREMENT_PHRASES),
                alternatives[0].replace("_", " ") if alternatives else "",
            )
        if phrase and phrase not in phrases:
            phrases.append(phrase)
    return " and ".join(phrases)


class ProcessingModule:
    """Base class for all processing modules"""

    NAME = "Module Base"
    DESCRIPTION = "Base processing module"
    VERSION = "1.0.0"
    CATEGORY = "misc"
    REQUIRES = []
    PRIORITY = 0
    EXPERIMENTAL = False

    def __init__(self):
        """Initialize the module"""
        self.processor = None
        self.logger = logging.getLogger(f"Module.{self.NAME}")

    def initialize(self):
        """Initialize module resources"""
        pass

    def document_workspace_keys(self) -> Dict[str, Dict[str, str]]:
        """
        Document workspace keys used by this module

        Returns:
            Dictionary mapping key names to their metadata
        """
        docs = {}

        # Document inputs
        for key in self.get_workspace_requirements():
            docs[key] = {
                "type": "input",
                "required": True,
                "description": f"Required by {self.NAME}",
            }

        # Document outputs
        for key in self.get_workspace_outputs():
            docs[key] = {
                "type": "output",
                "required": False,
                "description": f"Generated by {self.NAME}",
            }

        return docs

    def update_workspace(self, workspace, key: str, value: Any):
        """
        Safely update a workspace key with debug output

        Args:
            workspace: Current workspace (dict or Workspace)
            key: Key to update
            value: New value

        Returns:
            Updated workspace
        """
        # Store old value for debug
        old_value = workspace.get(key)

        workspace.set(key, value)

        # Debug output
        debug_flag = workspace.get("debug", False)
        if debug_flag and hasattr(self, "processor") and self.processor:
            self._debug_value(key, value, old_value, "updated")

        # If this module has a processor and the processor has an attribute with the same name,
        # update that attribute as well for backward compatibility
        if hasattr(self, "processor") and self.processor:
            if hasattr(self.processor, key):
                setattr(self.processor, key, value)

        # Notify the viewer coordinator on changes to registered structure
        # keys. We delegate to ``get_priority_pdb_file`` so the viewer
        # follows the same precedence the rest of ProPrep uses (see
        # ``utils.structure_selector.StructureRegistry``) — writing a
        # lower-priority key won't yank the viewer off a higher-priority
        # one already loaded, and the priority list is dynamic, so any
        # newly-registered structure type is automatically viewable.
        # Wrapped: a viewer hiccup must never cause a workspace update to fail.
        try:
            self._notify_viewer_if_structure_key(workspace, key, value, old_value)
        except Exception:
            pass

        return workspace

    def _notify_viewer_if_structure_key(
        self, workspace, key: str, value: Any, old_value: Any,
    ) -> None:
        # Lazy imports — avoid pulling structure_prep / structure_selector
        # at module-load time (cheap path for non-structure keys is the
        # registry lookup just below).
        from proprep.utils.structure_selector import StructureRegistry, get_priority_pdb_file
        from proprep.structure_prep.viewer_coordinator import viewer

        # Fast path: most workspace writes are not structure keys.
        if StructureRegistry.get(key) is None:
            return

        # ``value`` may be a path (str) for *_pdb_file keys, or a Structure
        # object for *_structure keys. Only path-typed registered keys are
        # something the viewer can render directly.
        priority_path = get_priority_pdb_file(workspace, silent=True)
        if not priority_path:
            return
        viewer.show_structure(priority_path)

    def _debug_value(self, key: str, value: Any, old_value: Any, action: str):
        """
        Debug output for value updates

        Args:
            key: Key being updated
            value: New value
            old_value: Previous value
            action: Action being performed
        """
        if key == "debug":
            return  # Don't debug the debug flag itself

        value_type = type(value).__name__
        if hasattr(value, "__len__") and not isinstance(value, (str, bytes)):
            value_info = f"{value_type}({len(value)})"
        else:
            value_info = value_type

        if old_value is None:
            self.logger.debug(
                f"{self.NAME} {action} new value for '{key}': {value_info}"
            )
        else:
            old_type = type(old_value).__name__
            if hasattr(old_value, "__len__") and not isinstance(
                old_value, (str, bytes)
            ):
                old_info = f"{old_type}({len(old_value)})"
            else:
                old_info = old_type

            self.logger.debug(
                f"{self.NAME} {action} '{key}' from {old_info} to {value_info}"
            )

    def update_workspace_batch(self, workspace, updates: Dict[str, Any]):
        """
        Update multiple workspace keys at once

        Args:
            workspace: Current workspace dictionary or Workspace object
            updates: Dictionary of updates

        Returns:
            Updated workspace
        """
        for key, value in updates.items():
            workspace = self.update_workspace(workspace, key, value)

        return workspace

    def set_processor(self, processor: Any):
        """Set the parent processor reference"""
        self.processor = processor

    def get_menu_options(self) -> Dict[str, str]:
        """Get module menu options"""
        return {}

    def handle_menu_option(self, option: str) -> bool:
        """Handle a menu option selection"""
        return False

    def get_workspace_requirements(self) -> List[str]:
        """Get workspace requirements"""
        return []

    def get_workspace_outputs(self) -> List[str]:
        """Get workspace outputs"""
        return []

    def can_process(self, workspace) -> bool:
        """
        Check if the module can process the current workspace

        Args:
            workspace: Current workspace dictionary or Workspace object

        Returns:
            True if all requirements are met, False otherwise
        """
        requirements = self.get_workspace_requirements()

        # Check if all required workspace keys are present and have values
        for req in requirements:
            if workspace.get(req) is None:
                return False

        return True

    def availability_note(self, workspace) -> Optional[str]:
        """Short reason this module is unavailable (its menu indicator
        is ○), or ``None`` when it can process.

        The menu shows this as a note under the description only when
        ``can_process()`` is False. The default derives the reason from
        ``get_workspace_requirements()`` (handling the pipe-OR syntax:
        an alternative group is satisfied if any one key is present).

        Modules that override ``can_process()`` with custom logic — or
        declare no requirements — should override this too; the robust
        pattern is::

            return None if self.can_process(ws) else "Needs ..."

        which guarantees the note can never disagree with the
        indicator. Returns ``None`` (no note) when no reason can be
        derived, so callers should treat ``None`` as "no extra note".
        """
        unmet = []
        for req in self.get_workspace_requirements():
            alternatives = [k.strip() for k in req.split("|") if k.strip()]
            if not any(workspace.get(alt) is not None for alt in alternatives):
                unmet.append(req)
        if not unmet:
            return None
        reason = _friendly_requirement(unmet)
        return f"Needs {reason}" if reason else None

    def process(self, workspace) -> Any:
        """
        Process the workspace

        Args:
            workspace: Current workspace to process

        Returns:
            Updated workspace
        """
        # Default implementation just returns the workspace unchanged
        return workspace

    def get_workspace_display(
        self, workspace_key: str, value: Any, console: Any
    ) -> bool:
        """
        Custom display method for module data in workspace

        Args:
            workspace_key: Key in the workspace
            value: Value for the key
            console: Rich console for output

        Returns:
            True if handled, False otherwise
        """
        return False

    def cleanup(self):
        """Clean up module resources"""
        pass

    def record_command(self, command):
        """
        Record a ModuleActionCommand for replay.
        Modules can override this for custom behavior.

        Note: Global command history is handled by the base Command class,
        """
        # Store locally for module-specific history
        if hasattr(self, "_local_command_history"):
            self._local_command_history.append(command)
        else:
            self._local_command_history = [command]

    def get_breadcrumb_for_command(self, command):
        """
        Return the breadcrumb string for a command. Override for custom breadcrumbs.
        """
        # Default: module_name.action_name
        if hasattr(command, "_action_to_run"):
            return f"{self.NAME}.{command._action_to_run}"
        return self.NAME


class ModuleRegistry:
    """Registry for processing modules"""

    def __init__(self):
        """Initialize the module registry"""
        self.modules: Dict[str, Type[ProcessingModule]] = {}
        self.instances: Dict[str, ProcessingModule] = {}
        self.logger = logging.getLogger(__name__)

    def register_module(self, module_class: Type[ProcessingModule], quiet=False):
        """Register a module class"""
        module_name = module_class.NAME
        self.modules[module_name] = module_class
        if not quiet:
            print(f"Registered module: {module_name}")

    def get_module(self, name: str) -> Optional[ProcessingModule]:
        """Get or create a module instance"""
        if name not in self.modules:
            return None

        if name not in self.instances:
            module_class = self.modules[name]
            self.instances[name] = module_class()

        return self.instances[name]

    def get_module_names(self) -> List[str]:
        """Get list of registered module names"""
        return list(self.modules.keys())

    def get_modules_by_category(self) -> Dict[str, List[str]]:
        """Get modules organized by category"""
        categories = {}

        for name, module_class in self.modules.items():
            category = module_class.CATEGORY
            if category not in categories:
                categories[category] = []
            categories[category].append(name)

        return categories

    def cleanup(self):
        """Clean up all module instances"""
        for module in self.instances.values():
            module.cleanup()

    def collect_workspace_key_inventory(self) -> Dict[str, Dict[str, List[str]]]:
        """
        Collect workspace key inventory from all registered modules.

        Iterates all registered modules, calling get_workspace_outputs() and
        get_workspace_requirements() to build a map of key names to their
        producer/consumer modules.

        Returns:
            Dict with structure:
            {
                "key_name": {
                    "produced_by": ["Module Name", ...],
                    "required_by": ["Module Name", ...],
                }
            }
        """
        inventory: Dict[str, Dict[str, List[str]]] = {}

        for name in self.get_module_names():
            module = self.get_module(name)
            if module is None:
                continue

            # Collect outputs (keys this module produces)
            for key in module.get_workspace_outputs():
                if key not in inventory:
                    inventory[key] = {"produced_by": [], "required_by": []}
                inventory[key]["produced_by"].append(name)

            # Collect requirements (keys this module consumes)
            # Handle pipe syntax: "key_a | key_b" means either key satisfies
            for req in module.get_workspace_requirements():
                alternatives = [k.strip() for k in req.split("|")]
                for key in alternatives:
                    if not key:
                        continue
                    if key not in inventory:
                        inventory[key] = {"produced_by": [], "required_by": []}
                    inventory[key]["required_by"].append(name)

        return inventory


# Global registry instance
registry = ModuleRegistry()


def register_module(cls):
    """Decorator to register a module class"""
    registry.register_module(cls, quiet=True)
    return cls
